/*
 ***********************************************************************************************************
 * @file
 * c__series_meta.sql
 *
 * Control table - series metadata, updated by triggers on c_series and maintained by users/apps.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c__series_meta;

CREATE TABLE IF NOT EXISTS ce_warehouse.c__series_meta
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_series INT NOT NULL,  -- see Foreign key constraint below

    ifreq SMALLINT NOT NULL
        CHECK (ifreq IN (1, 2, 3 , 4, 5)),
    itype SMALLINT NOT NULL
        CHECK (itype IN (1, 2)),

    -- SID1 is on the "series" level, SID2 and SID3 are on the "series+frequency+type" level
    sid1 TEXT NOT NULL,
    sid2 TEXT NOT NULL GENERATED ALWAYS
        AS (sid1 || '_' || ce_warehouse.fx_ut__freq_code(ifreq)) STORED,
    -- Can base on SID2 as: a generated column can reference another generated column,
    -- as long as the dependency chain is valid and not cyclic
    sid3 TEXT NOT NULL GENERATED ALWAYS
        AS (sid2 || '_' || ce_warehouse.fx_ut__type_code(itype)) STORED,

    -- User maintained fields
    downloadable TEXT NOT NULL DEFAULT 'ess_plugin'
        CHECK (
            downloadable IN (
                'all',
                'api',
                'adv_plugin',
                'ess_plugin',
                'internal',
                'none',
                'powerbi')
        ),
    forecast_only_lifespan INT,  -- If NULL then will take the system default
    internal_notes TEXT,  -- Unvalidated!

    ts_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (sid3),  -- enforce unique SID3

    -- Composite foreign key
    FOREIGN KEY (fk_pk_series, sid1)
        REFERENCES c__series (pk_series, sid1)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

-- It's recommended to have INDICES on foreign keys for performance!!
CREATE INDEX IF NOT EXISTS c__series_meta__series__idx
    ON ce_warehouse.c__series_meta (fk_pk_series, sid1);

-- For performance!!
CREATE INDEX IF NOT EXISTS c__series_meta__sid1__idx
    ON ce_warehouse.c__series_meta (sid1);

CREATE INDEX IF NOT EXISTS c__series_meta__sid2__idx
    ON ce_warehouse.c__series_meta (sid2);

COMMENT ON TABLE ce_warehouse.c__series_meta
    IS 'Control table - series metadata, updated by triggers on c_series and maintained by users/apps';
