/*
 ***********************************************************************************************************
 * @file
 * c_api_calc.sql
 *
 * Control table - calculated values/series, API (& manual) table.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_etl.c_api_calc;

CREATE TABLE IF NOT EXISTS ce_etl.c_api_calc
(
    pk_api_calc INT GENERATED BY DEFAULT AS IDENTITY,
    ca_target_series TEXT NOT NULL,  -- Target Series ID
    ca_target_freq TEXT[] NOT NULL,  -- Target Frequencies
    ca_target_freq_int INT[] GENERATED ALWAYS AS (ce_etl.fx_ut_ifreq_multi(ca_target_freq)) STORED,
    ca_source_series TEXT NOT NULL,  -- Source Series ID, cant be based on "calculated"
    ca_source_freq TEXT NOT NULL,  -- Source Frequency
    ca_source_freq_int INT GENERATED ALWAYS AS (ce_etl.fx_ut_ifreq_single(ca_source_freq)) STORED,
    ca_formula_type TEXT NOT NULL,  -- Formula Type: peop/psum/pmean
    internal_notes TEXT,  -- Internal notes, unvalidated!
    error TEXT,
    regenerate BOOLEAN NOT NULL DEFAULT TRUE,  -- Does this series need regenerating?
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (pk_api_calc),
    UNIQUE (ca_target_series)
);

COMMENT ON TABLE ce_etl.c_api_calc
    IS 'Control table - calculated values/series, API (& manual) table';
