/*
 ***********************************************************************************************************
 * @file
 * c_calc.sql
 *
 * Control table - calculated values/series.
 *
 * This replaces the old c_ctl1/ctl2 tables. Initially the supported calculations will be:
 *
 * - simple calculations, e.g. #ABC_XYZ# * 2, multiple series can be specified
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_etl.c_calc;

CREATE TABLE IF NOT EXISTS ce_etl.c_calc
(
    pk_calc INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    calc_series TEXT NOT NULL,  -- Series ID
    calc_freq TEXT NOT NULL,  -- Frequency
    calc_type TEXT NOT NULL,  -- AC/F/BLENDED
    calc_formula TEXT NOT NULL,
    internal_notes TEXT,  -- Internal notes, unvalidated!
    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (pk_calc),
    UNIQUE (con_code)
);

CREATE UNIQUE INDEX IF NOT EXISTS c_calc__unique_index
    ON ce_data.c_calc (calc_series,  calc_freq, calc_type);

COMMENT ON TABLE ce_data.c_calc
    IS 'Control table - calculated values/series control table';
