/*
 ***********************************************************************************************************
 * @file
 * c_calc.sql
 *
 * Control table - "rules" for calculated values (AC/F/BLENDED).
 *
 * Initially the supported calculations will be:
 *
 * - simple calculations, e.g. #ABC_XYZ# * 2, multiple series can be specified
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_etl.c_calc;

CREATE TABLE IF NOT EXISTS ce_etl.c_calc
(
    pk_calc INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    calc_series TEXT NOT NULL,  -- Series ID
    calc_freq TEXT NOT NULL,  -- Frequency
    calc_type TEXT NOT NULL,  -- AC/F/BLENDED
    calc_formula TEXT NOT NULL,
    internal_notes TEXT,  -- Internal notes, unvalidated!
    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (pk_calc),
    UNIQUE (calc_series,  calc_freq, calc_type)
);

COMMENT ON TABLE ce_etl.c_calc
    IS 'Control table - "rules" for calculated values (AC/F/BLENDED)';
