/*
 ***********************************************************************************************************
 * @file
 * c_series_meta.sql
 *
 * Control table - series metadata, additional information on a series/freq/type basis.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_etl.c_series_meta;

CREATE TABLE IF NOT EXISTS ce_etl.c_series_meta
(
    pk_sm INT GENERATED BY DEFAULT AS IDENTITY,
    sm_gcode TEXT NOT NULL,
    sm_icode TEXT NOT NULL,
    sm_freq TEXT,
    sm_type TEXT,
    sm_downloadable TEXT NOT NULL DEFAULT 'ess_plugin'
        CHECK (sm_downloadable IN ('all', 'api', 'adv_plugin', 'ess_plugin', 'internal', 'none', 'powerbi')),  -- control which series are downloadable and via which channels
    forecast_only_lifespan INT,  -- If NULL then will take the system default from s_freq
    internal_notes TEXT,  -- Internal notes, unvalidated!
    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (pk_sm),
    UNIQUE (sm_gcode, sm_icode, sm_freq, sm_type)
);

COMMENT ON TABLE ce_etl.c_series_meta
    IS 'Control table - series metadata, additional information on a series/freq/type basis';
