/*
 ***********************************************************************************************************
 * @file
 * x_series_value.sql
 *
 * Internal table - series values summary/metadata.
 *
 * Maintained by trigger updates, can also be built up from x_value + audit trail.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_etl.x_series_value;

CREATE TABLE IF NOT EXISTS ce_etl.x_series_value
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fk_pk_s INT NOT NULL
        REFERENCES ce_etl.c_series (pk_s)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    freq SMALLINT
        REFERENCES ce_etl.l_freq (pk_f),
    type SMALLINT NOT NULL
        REFERENCES ce_etl.l_type (pk_t),
    new_values_utc TIMESTAMPTZ,  -- timestamp of the most recent new value
    updated_values_utc TIMESTAMPTZ,  -- timestamp of the most recent updated (or deleted) value
    PRIMARY KEY (idx),
    UNIQUE (fk_pk_s, freq, type)  -- per series/frequency/type
);

COMMENT ON TABLE ce_etl.x_series_value
    IS 'Internal table - series values summary/metadata';
