/*
 ***********************************************************************************************************
 * @file
 * x_tooltip.sql
 *
 * Internal table - tooltip values.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_etl.x_tooltip;

CREATE TABLE IF NOT EXISTS ce_etl.x_tooltip
(
    pk_tip INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tooltip TEXT NOT NULL,
    PRIMARY KEY(pk_tip),
    UNIQUE (tooltip)
);

COMMENT ON TABLE ce_etl.x_tooltip
    IS 'Internal table - Tooltip values';
