/*
 ***********************************************************************************************************
 * @file
 * x_value.sql
 *
 * Internal table - datapoint values.
 *
 * Note, this table is built up incrementally.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_etl.x_values;

CREATE TABLE IF NOT EXISTS ce_etl.x_values
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fk_pk_s INT NOT NULL
        REFERENCES ce_etl.c_series (pk_s),
    pdi INT NOT NULL
        REFERENCES ce_etl.l_period (pk_p),
    type SMALLINT NOT NULL
        REFERENCES ce_etl.l_type (pk_t),
    freq SMALLINT NOT NULL GENERATED ALWAYS
        AS (pdi / 100000000) STORED,  -- extract frequency from period code
    source TEXT NOT NULL,
    value NUMERIC NOT NULL,
    fk_pk_tip INT
        REFERENCES ce_etl.x_tooltip (pk_tip),  -- optional tooltip reference
    is_calculated BOOLEAN NOT NULL GENERATED ALWAYS
        AS (source ~ '^X') STORED,  -- flag to indicate if the value is calculated
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (idx),
    UNIQUE (fk_pk_s, pdi)  -- enforce only one value per period
);

COMMENT ON TABLE ce_etl.x_api
    IS 'Internal table - datapoint values';
