/*
 ***********************************************************************************************************
 * @file
 * x_value.sql
 *
 * Internal table - datapoint values.
 *
 * Note: (a) this table is built up incrementally, (b) foreign refs are handled by housekeeping apps.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_etl.x_value;

CREATE TABLE IF NOT EXISTS ce_etl.x_value
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fk_pk_s INT NOT NULL
        REFERENCES ce_etl.c_series (pk_s)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    pdi INT NOT NULL,  -- reference to period identifier, see housekeeping
    freq SMALLINT NOT NULL GENERATED ALWAYS
        AS (pdi / 100000000) STORED,  -- extract frequency from period code
    type SMALLINT NOT NULL
        REFERENCES ce_etl.l_type (pk_t),
    source TEXT NOT NULL,
    value NUMERIC NOT NULL,
    fk_pk_tip INT
        REFERENCES ce_etl.x_tooltip (pk_tip)
        ON UPDATE CASCADE
        ON DELETE SET NULL,  -- optional tooltip reference
    is_calculated BOOLEAN NOT NULL GENERATED ALWAYS
        AS (source ~ '^X') STORED,  -- flag to indicate if the value is calculated
    error TEXT,  -- optional error message for invalid values, there should never be any!!
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (idx),
    UNIQUE (fk_pk_s, pdi)  -- enforce only one value per period
);

COMMENT ON TABLE ce_etl.x_value
    IS 'Internal table - datapoint values';
