/*
 ***********************************************************************************************************
 * @file
 * l_value_range.sql
 *
 * Lookup table - value "range" lookup.
 * Can be used to define valid ranges for values.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l__value_range;

CREATE TABLE IF NOT EXISTS ce_warehouse.l__value_range
(
    pk_value_range INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val__is_text(name) IS NULL),

    min_value BIGINT NOT NULL,
    max_value BIGINT NOT NULL,
    
    ordering SMALLINT DEFAULT 0,
    
    PRIMARY KEY (pk_value_range),
    UNIQUE (name)
);

COMMENT ON TABLE ce_warehouse.l__value_range
    IS 'Lookup table - value "range" lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l__value_range
(name, min_value, max_value, ordering)
VALUES
    ('ANY (default)', -POWER(10,16)::BIGINT, POWER(10,16)::BIGINT, 0),
    
    -- ANY +ve or -ve value (up to 10^15, which is 1 quadrillion, more than enough for most use cases)
    ('<= 0', -POWER(10,16)::BIGINT, 0, 1),
    ('>= 0', 0, POWER(10,16)::BIGINT, 1),
    
    -- Percentages
    ('-100..100 %', -100, 100, 2),
    ('-100..0 %', -100, 0, 2),
    ('0..+100 %', 0, 100, 2),
    
    -- -1 to +1
    ('-1..+1', -1, 1, 3),
    ('-1..0', -1, 0, 3),
    ('0..+1', 0, 1, 3),
    
    -- -10 to +10
    ('-10..+10', -10, 10, 4),
    ('-10..0', -10, 0, 4),
    ('0..+10', 0, 10, 4),
    
    -- -100 to +100
    ('-100..+100', -100, 100, 5),
    ('-100..0', -100, 0, 5),
    ('0..+100', 0, 100, 5),
    
    -- -1K to +1K
    ('-1K..+1K', -1000, 1000, 6),
    ('-1K..0', -1000, 0, 6),
    ('0..+1K', 0, 1000, 6),
    
    -- -10K to +10K
    ('-10K..+10K', -POWER(10,4)::BIGINT, POWER(10,4)::BIGINT, 7),
    ('-10K..0', -POWER(10,4)::BIGINT, 0, 7),
    ('0..+10K', 0, POWER(10,4)::BIGINT, 7),
    
    -- -100K to +100K
    ('-100K..+100K', -POWER(10,6)::BIGINT, POWER(10,6)::BIGINT, 8),
    ('-100K..0', -POWER(10,6)::BIGINT, 0, 8),
    ('0..+100K', 0, POWER(10,6)::BIGINT, 8),
    
    -- -1M to +1M
    ('-1M..+1M', -POWER(10,7)::BIGINT, POWER(10,7)::BIGINT, 9),
    ('-1M..0', -POWER(10,7)::BIGINT, 0, 9),
    ('0..+1M', 0, POWER(10,7)::BIGINT, 9),
    
    -- -1B to +1B
    ('-1B..+1B', -POWER(10,10)::BIGINT, POWER(10,10)::BIGINT, 10),
    ('-1B..0', -POWER(10,10)::BIGINT, 0, 10),
    ('0..+1B', 0, POWER(10,10)::BIGINT, 10);