/*
 ***********************************************************************************************************
 * @file
 * a__xvalue.sql
 *
 * Audit table - datapoint values.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.a__xvalue;

CREATE TABLE IF NOT EXISTS ce_warehouse.a__xvalue
(
    idx BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_series INT NOT NULL,
    lk_pk_pdi INT,
    ifreq INT GENERATED ALWAYS
        AS (
            CASE
                WHEN lk_pk_pdi > 0 THEN (lk_pk_pdi / 100000000)
                ELSE NULL
            END
        ) STORED,
    itype INT,
    lk_pk_source INT,
    value NUMERIC,
    new_value NUMERIC,  -- for updates, store the new value for debugging!
    is_realised BOOL,

    audit_type TEXT NOT NULL
        CHECK (audit_type IN ('I', 'U', 'D', 'init', 'pipeline')),

    audit_user TEXT NOT NULL
        CHECK (ce_warehouse.fx_val__is_audit_user(audit_user) IS NULL),

    ts_audit_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx)
);

CREATE INDEX IF NOT EXISTS a__xvalue__datapoint__idx
    ON ce_warehouse.a__xvalue (fk_pk_series, lk_pk_pdi, idx DESC);

COMMENT ON TABLE ce_warehouse.a__xvalue
    IS 'Audit table - datapoint values';
