/*
 ***********************************************************************************************************
 * @file
 * a__gen_audit.sql
 *
 * Audit table - generic audit table.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.a__gen_audit;

CREATE TABLE IF NOT EXISTS ce_warehouse.a__gen_audit
(
    idx BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    t_name TEXT NOT NULL,  -- for debugging, store the name of the table being audited
    t_pkey TEXT NOT NULL,  -- store the PK of the record being audited, for debugging/reference
    data JSONB,  -- store the full record data as JSONB for flexibility and debugging,

    audit_type TEXT NOT NULL
        CHECK (audit_type IN ('I', 'U', 'D')),
    ts_audit_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx)
);

CREATE INDEX IF NOT EXISTS a__gen_audit__table_name__idx
    ON ce_warehouse.a__gen_audit (t_name, t_pkey, idx DESC);  -- index to optimize queries for specific tables/records, with most recent changes first

COMMENT ON TABLE ce_warehouse.a__gen_audit
    IS 'Audit table - generic audit table';
