/*
 ***********************************************************************************************************
 * @file
 * a_audit.sql
 *
 * Audit table - generic audit table.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.a_audit;

CREATE TABLE IF NOT EXISTS ce_warehouse.a_audit
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    table_name TEXT NOT NULL,  -- for debugging, store the name of the table being audited
    table_pk TEXT NOT NULL,  -- store the PK of the record being audited, for debugging/reference
    data JSONB,  -- store the full record data as JSONB for flexibility and debugging,

    audit_type TEXT NOT NULL
        CHECK (audit_type IN ('I', 'U', 'D')),
    audit_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx)
);

CREATE INDEX IF NOT EXISTS a_audit__table__idx
    ON ce_warehouse.a_audit (table_name, table_pk, idx DESC);  -- index to optimize queries for specific tables/records, with most recent changes first

COMMENT ON TABLE ce_warehouse.a_audit
    IS 'Audit table - generic audit table';
