/*
 ***********************************************************************************************************
 * @file
 * a_c_series.sql
 *
 * Audit table - partial series data.
 * Note, we're only actually interested if (a) the series is DELETED or (b) the series ID changes.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.a_c_series;

CREATE TABLE IF NOT EXISTS ce_warehouse.a_c_series
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,
    pk_s INT,
    s_series_id TEXT,
    audit_type TEXT NOT NULL
        CHECK (audit_type IN ('U', 'D')),
    audit_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (idx)
);

COMMENT ON TABLE ce_warehouse.a_c_series
    IS 'Audit table - partial series data';
