/*
 ***********************************************************************************************************
 * @file
 * a_x_value.sql
 *
 * Audit table - datapoint values.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.a_x_value;

CREATE TABLE IF NOT EXISTS ce_warehouse.a_x_value
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fk_pk_s INT NOT NULL,
    pdi INT,
    type SMALLINT,
    freq SMALLINT GENERATED ALWAYS AS (
      CASE
        WHEN pdi > 0 THEN (pdi / 100000000)
      END
    ) STORED,
    source SMALLINT,
    value NUMERIC,
    new_value NUMERIC,  -- for updates, store the new value for debugging!
    realised BOOLEAN,
    audit_type TEXT NOT NULL
        CHECK (audit_type IN ('I', 'U', 'D', 'init', 'pipeline')),
    audit_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx)
);

CREATE INDEX IF NOT EXISTS a_x_value__datapoint__idx
    ON ce_warehouse.a_x_value (fk_pk_s, pdi, idx DESC);

COMMENT ON TABLE ce_warehouse.a_x_value
    IS 'Audit table - datapoint values';
