/*
 ***********************************************************************************************************
 * @file
 * c_calc.sql
 *
 * Control table - "rules" for calculated values (vers 2).
 * Handles both API calc & the more custom calculations, with the aim of simplifying logic & maintenance.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c__calc;

CREATE TABLE IF NOT EXISTS ce_warehouse.c__calc
(
    pk_calc INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    tgt_series_id TEXT NOT NULL
        REFERENCES ce_warehouse.c__series(series_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,
    tgt_cfreq TEXT NOT NULL
        CHECK (tgt_cfreq IN ('D', 'W', 'M', 'Q', 'Y')),
    tgt_ctype TEXT NOT NULL
        CHECK (tgt_ctype IN ('AC', 'F')),

    formula_type TEXT NOT NULL
        REFERENCES ce_warehouse.s__formula_type(code)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    expr TEXT NOT NULL,  -- Validated via APP

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val__is_text(internal_notes, 'internal_notes') IS NULL),

    error TEXT,  -- system generated
    ts_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_calc),
    UNIQUE (tgt_series_id, tgt_cfreq, tgt_ctype)
);

-- It's recommended to have INDICES on foreign keys for performance!!
-- unless we already have them on the referenced table
CREATE INDEX IF NOT EXISTS c_calc__formula_type__idx
    ON ce_warehouse.c__calc (formula_type);

COMMENT ON TABLE ce_warehouse.c__calc
    IS 'Control table - "rules" for calculated values (vers 2)';
