/*
 ***********************************************************************************************************
 * @file
 * c_geo.sql
 *
 * Control table - geography & commodity details, used for validation & extra detail.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c__geo;

CREATE TABLE IF NOT EXISTS ce_warehouse.c__geo
(
    pk_geo INT GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (code = 'INTERNAL' OR code ~ '^[GC]\.[A-Z][A-Z0-9_]*[A-Z0-9]$'),

    short_code TEXT NOT NULL GENERATED ALWAYS
        AS (
            CASE
                WHEN code = 'INTERNAL' THEN 'n/a'
                ELSE SUBSTRING(code, 3)
            END
        ) STORED,
    geo_type TEXT NOT NULL GENERATED ALWAYS
        AS (
            CASE
                WHEN code LIKE 'G.%' THEN 'Geography'
                WHEN code LIKE 'C.%' THEN 'Commodity'
                WHEN code = 'INTERNAL' THEN 'Internal Use'
                ELSE NULL  -- this should never happen due to the CHECK constraint on code
            END
        ) STORED,

    -- Fields common to both GEO & COM
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val__is_name(name, 'c_geo.name', FALSE) IS NULL),
    short_name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val__is_name(short_name, 'c_geo.short_name', FALSE) IS NULL),
    tla TEXT NOT NULL
        CHECK (ce_warehouse.fx_val__is_name(tla, 'c_geo.tla', FALSE) IS NULL),

    ordering INT NOT NULL DEFAULT 0,

    -- COM specific fields (will be NULL for GEO)
    lk_pk_commodity_type SMALLINT
        REFERENCES ce_warehouse.l__com_type(pk_com_type)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code LIKE 'C.%' AND lk_pk_commodity_type IS NOT NULL)
            OR (code NOT LIKE 'C.%' AND lk_pk_commodity_type IS NULL)
        ),

    -- GEO specific fields (will be NULL for COM)
    name2 TEXT
        CHECK (
            (code NOT LIKE 'G.%' AND name2 IS NULL)
            OR (
                code LIKE 'G.%'
                AND ce_warehouse.fx_val__is_name(name2, 'c_geo.name2', FALSE) IS NULL
            )
        ),
    iso2 TEXT
        CHECK (
            (code NOT LIKE 'G.%' AND iso2 IS NULL)
            OR (code LIKE 'G.%' AND (iso2 IS NULL OR iso2 ~ '^[A-Z]{2}$'))
        ),
    iso3 TEXT
        CHECK (
            (code NOT LIKE 'G.%' AND iso3 IS NULL)
            OR (code LIKE 'G.%' AND (iso3 IS NULL OR iso3 ~ '^[A-Z]{3}$'))
        ),
    lat NUMERIC
        CHECK (
            (code NOT LIKE 'G.%' AND lat IS NULL)
            OR (code LIKE 'G.%' AND (lat IS NULL OR lat BETWEEN -90 AND 90))
        ),
    long NUMERIC
        CHECK (
            (code NOT LIKE 'G.%' AND long IS NULL)
            OR (code LIKE 'G.%' AND (long IS NULL OR long BETWEEN -180 AND 180))
        ),
    lk_pk_central_bank SMALLINT
        REFERENCES ce_warehouse.l__central_bank(pk_central_bank)
            ON UPDATE RESTRICT
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code NOT LIKE 'G.%' AND lk_pk_central_bank IS NULL)
            OR code LIKE 'G.%'
        ),
    lk_pk_stock_market SMALLINT
        REFERENCES ce_warehouse.l__stock_market(pk_stock_market)
            ON UPDATE RESTRICT
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code NOT LIKE 'G.%' AND lk_pk_stock_market IS NULL)
            OR code LIKE 'G.%'
        ),
    lk_pk_political_alignment SMALLINT
        REFERENCES ce_warehouse.l__political_alignment(pk_political_alignment)
            ON UPDATE RESTRICT
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code NOT LIKE 'G.%' AND lk_pk_political_alignment IS NULL)
            OR code LIKE 'G.%'
        ),
    lk_pk_currency_unit SMALLINT
        REFERENCES ce_warehouse.l__currency_unit(pk_currency_unit)
            ON UPDATE RESTRICT
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code NOT LIKE 'G.%' AND lk_pk_currency_unit IS NULL)
            OR code LIKE 'G.%'
        ),
    flag TEXT
        CHECK (
                (code NOT LIKE 'G.%' AND flag IS NULL)
                OR (code LIKE 'G.%' AND ce_warehouse.fx_val__is_name(flag, 'c_geo.flag') IS NULL)
        ),
    lk_pk_geo_category SMALLINT
        REFERENCES ce_warehouse.l__geo_category(pk_geo_category)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
                (code NOT LIKE 'G.%' AND lk_pk_geo_category IS NULL)
                OR (code LIKE 'G.%' AND lk_pk_geo_category IS NOT NULL)
        ),

    -- Standard fields
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (
            status IN ('active', 'inactive', 'deleted')
            AND (
                (code = 'INTERNAL' AND status <> 'deleted')  -- INTERNAL record cannot be deleted
                OR code <> 'INTERNAL'
            )
        ),
    internal_notes TEXT
        CHECK (ce_warehouse.fx_val__is_text(internal_notes, 'internal_notes') IS NULL),

    error TEXT,  -- system generated
    ts_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_geo),
    UNIQUE (code),
    UNIQUE (short_code)
);

-- It's recommended to have INDICES on foreign keys for performance!!
CREATE INDEX IF NOT EXISTS c_geo__commodity_type__idx
    ON ce_warehouse.c__geo (lk_pk_commodity_type);

CREATE INDEX IF NOT EXISTS c_geo__central_bank__idx
    ON ce_warehouse.c__geo (lk_pk_central_bank);

CREATE INDEX IF NOT EXISTS c_geo__stock_market__idx
    ON ce_warehouse.c__geo (lk_pk_stock_market);

CREATE INDEX IF NOT EXISTS c_geo__political_alignment__idx
    ON ce_warehouse.c__geo (lk_pk_political_alignment);

CREATE INDEX IF NOT EXISTS c_geo__local_currency_unit__idx
    ON ce_warehouse.c__geo (lk_pk_currency_unit);

CREATE INDEX IF NOT EXISTS c_geo__category__idx
    ON ce_warehouse.c__geo (lk_pk_geo_category);

COMMENT ON TABLE ce_warehouse.c__geo
    IS 'Control table - geography details, used for validation & extra detail';

/**
 * Pre-populate with System Use values.
 */
INSERT INTO ce_warehouse.c__geo (pk_geo, code, name, short_name, tla, internal_notes)
VALUES
    (-1, 'INTERNAL', 'For internal use series etc', 'n/a', 'n/a', 'Allows declaration of internal use series');

/*
 ***********************************************************************************************************
 * Block any updates to system records
 ***********************************************************************************************************
 */

-- DROP TRIGGER IF EXISTS tg__cgeo__b01 ON ce_warehouse.c__geo;

CREATE TRIGGER tg__cgeo__b01
    BEFORE UPDATE OR DELETE
        ON ce_warehouse.c__geo
    FOR EACH ROW
        EXECUTE FUNCTION ce_warehouse.fx_tg__generic__block_internal('pk_geo');

COMMENT ON TRIGGER tg__cgeo__b01 ON ce_warehouse.c__geo
    IS 'Trigger to block changes to system records on c_geo table';

/*
 ***********************************************************************************************************
 * Soft "DELETE"
 ***********************************************************************************************************
 */

-- DROP TRIGGER IF EXISTS tg__cgeo__b02 ON ce_warehouse.c__geo;

CREATE TRIGGER tg__cgeo__b02
    BEFORE UPDATE OR DELETE
        ON ce_warehouse.c__geo
    FOR EACH ROW
        EXECUTE FUNCTION ce_warehouse.fx_tg__cgeo__soft_delete();

COMMENT ON TRIGGER tg__cgeo__b02 ON ce_warehouse.c__geo
    IS 'Trigger to instigate soft delete on c_geo table';
