/*
 ***********************************************************************************************************
 * @file
 * c_geo_group.sql
 *
 * Control table - GEO groups.
 * Replaces the "groups" array in c_geo with a more structured table, allowing for better maintenance.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c__geo_group;

CREATE TABLE IF NOT EXISTS ce_warehouse.c__geo_group
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_geo INT NOT NULL
        REFERENCES ce_warehouse.c__geo (pk_geo)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED
        CHECK(
            fk_pk_geo > 0 AND
            ce_warehouse.fx_val__is_geo_or_com(fk_pk_geo, 'geo') IS NULL
    ),

    -- GEO Group ID
    lk_pk_geo_group SMALLINT NOT NULL
        REFERENCES ce_warehouse.l__geo_group (pk_geo_group)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,

    error TEXT,  -- system generated
    ts_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_geo, lk_pk_geo_group)
);

-- It's recommended to have INDICES on foreign keys for performance!!
-- unless we already have them on the referenced table
CREATE INDEX IF NOT EXISTS c_geo_group__geo_group__idx
    ON ce_warehouse.c__geo_group (lk_pk_geo_group);

COMMENT ON TABLE ce_warehouse.c__geo_group
    IS 'Control table - GEO groups';
