/*
 ***********************************************************************************************************
 * @file
 * c_ind.sql
 *
 * Control table - indicator details, used for validation & lookup.
 *
 * Defined as a control table because it's details pass into PowerBi schema.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c__ind;

CREATE TABLE IF NOT EXISTS ce_warehouse.c__ind
(
    pk_ind INT GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (ce_warehouse.fx_val__is_code(code, 'c_ind.code', FALSE) IS NULL),
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val__is_name(name, 'c_ind.name', FALSE) IS NULL),
    description TEXT
        CHECK (ce_warehouse.fx_val__is_text(description, 'c_ind.description') IS NULL),
    name1 TEXT
        CHECK (ce_warehouse.fx_val__is_name(name1, 'c_ind.name1') IS NULL),
    name2 TEXT
        CHECK (ce_warehouse.fx_val__is_name(name2, 'c_ind.name2') IS NULL),
    name3 TEXT
        CHECK (ce_warehouse.fx_val__is_name(name3, 'c_ind.name3') IS NULL),
    name4 TEXT
        CHECK (ce_warehouse.fx_val__is_name(name4, 'c_ind.name4') IS NULL),
    name_lower TEXT
        CHECK (ce_warehouse.fx_val__is_name(name_lower, 'c_ind.name_lower.ignore_case') IS NULL),
    name1_lower TEXT
        CHECK (ce_warehouse.fx_val__is_name(name1_lower, 'c_ind.name1_lower.ignore_case') IS NULL),
    name2_lower TEXT
        CHECK (ce_warehouse.fx_val__is_name(name2_lower, 'c_ind.name2_lower.ignore_case') IS NULL),
    name3_lower TEXT
        CHECK (ce_warehouse.fx_val__is_name(name3_lower, 'c_ind.name3_lower.ignore_case') IS NULL),
    name4_lower TEXT
        CHECK (ce_warehouse.fx_val__is_name(name4_lower, 'c_ind.name4_lower.ignore_case') IS NULL),
    lk_ind_category_broad SMALLINT
        REFERENCES ce_warehouse.l__ind_category_broad (pk_ind_category_broad)
            ON UPDATE RESTRICT
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,
    lk_ind_category_narrow SMALLINT
        REFERENCES ce_warehouse.l__ind_category_narrow (pk_ind_category_narrow)
            ON UPDATE RESTRICT
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,
    lk_data_transformation SMALLINT NOT NULL
        REFERENCES ce_warehouse.l__data_transformation (pk_data_transformation)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    is_keyindicator BOOL NOT NULL DEFAULT FALSE,
    is_proprietary_data BOOL NOT NULL DEFAULT FALSE,
    ordering INT NOT NULL DEFAULT 0,

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive', 'deleted')),

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val__is_text(internal_notes, 'internal_notes') IS NULL),

    error TEXT,  -- system generated
    ts_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_ind),
    UNIQUE (code)
);

-- It's recommended to have INDICES on foreign keys for performance!!
CREATE INDEX IF NOT EXISTS c_ind__category_broad__idx
    ON ce_warehouse.c__ind (lk_ind_category_broad);

CREATE INDEX IF NOT EXISTS c_ind__category_narrow__idx
    ON ce_warehouse.c__ind (lk_ind_category_narrow);

CREATE INDEX IF NOT EXISTS c_ind__data_transformation__idx
    ON ce_warehouse.c__ind (lk_data_transformation);

COMMENT ON TABLE ce_warehouse.c__ind
    IS 'Control table - indicator details, used for validation & lookup';

/*
 ***********************************************************************************************************
 * Block any updates to system records, there are none currently!!
 ***********************************************************************************************************
 */

-- DROP TRIGGER IF EXISTS tg__cind__b01 ON ce_warehouse.c__ind;

CREATE TRIGGER tg__cind__b01
    BEFORE UPDATE OR DELETE
        ON ce_warehouse.c__ind
    FOR EACH ROW
        EXECUTE FUNCTION ce_warehouse.fx_tg__generic__block_internal('pk_ind');

COMMENT ON TRIGGER tg__cind__b01 ON ce_warehouse.c__ind
    IS 'Trigger to block changes to system records on c_ind table';

/*
 ***********************************************************************************************************
 * Soft "DELETE"
 ***********************************************************************************************************
 */

-- DROP TRIGGER IF EXISTS tg__cind__b02 ON ce_warehouse.c__ind;

CREATE TRIGGER tg__cind__b02
    BEFORE UPDATE OR DELETE
        ON ce_warehouse.c__ind
    FOR EACH ROW
        EXECUTE FUNCTION ce_warehouse.fx_tg__cind__soft_delete();

COMMENT ON TRIGGER tg__cind__b02 ON ce_warehouse.c__ind
    IS 'Trigger to instigate soft delete on c_ind table';
