/*
 ***********************************************************************************************************
 * @file
 * c_series_downloadable.sql
 *
 * Control table - series downloadable flags etc.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c__series_downloadable;

CREATE TABLE IF NOT EXISTS ce_warehouse.c__series_downloadable
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_series INT NOT NULL
        REFERENCES ce_warehouse.c__series (pk_series)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED
        CHECK (fk_pk_series > 0),
    ifreq SMALLINT NOT NULL
        CHECK (ifreq IN (1, 2, 3, 4, 5)),
    itype SMALLINT NOT NULL,
        CHECK (itype IN (1, 2)),

    -- User maintained fields
    downloadable TEXT NOT NULL DEFAULT 'ess_plugin'
        CHECK (
            downloadable IN (
                'all',
                'api',
                'adv_plugin',
                'ess_plugin',
                'internal',
                'none',
                'powerbi')
        ),
    forecast_only_lifespan INT,  -- If NULL then will take the system default
    internal_notes TEXT,  -- Unvalidated!

    error TEXT,  -- system generated
    ts_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_series, ifreq, itype)
);

COMMENT ON TABLE ce_warehouse.c__series_downloadable
    IS 'Control table - series downloadable flags etc';
