/*
 ***********************************************************************************************************
 * @file
 * c_series_data_source.sql
 *
 * Control table - series data sources.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c__series_data_source;

CREATE TABLE IF NOT EXISTS ce_warehouse.c__series_data_source
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_series INT NOT NULL
        REFERENCES ce_warehouse.c__series (pk_series)
            ON UPDATE CASCADE
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED
        CHECK (fk_pk_series > 0),

    -- Data source ID
    lk_pk_data_source SMALLINT NOT NULL
        REFERENCES ce_warehouse.l__data_source (pk_data_source)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,

    error TEXT,  -- system generated
    ts_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_series, lk_pk_data_source)
);

-- It's recommended to have INDICES on foreign keys for performance!!
-- unless we already have them on the referenced table
CREATE INDEX IF NOT EXISTS c_series_data_source__data_source__idx
    ON ce_warehouse.c__series_data_source (lk_pk_data_source);

COMMENT ON TABLE ce_warehouse.c__series_data_source
    IS 'Control table - series data sources';
