/*
 ***********************************************************************************************************
 * @file
 * c_api_calc.sql
 *
 * Control table - "rules" for calculated values (AC-only).
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_api_calc;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_api_calc
(
    pk_api_calc INT GENERATED BY DEFAULT AS IDENTITY,

    tgt_series_id TEXT NOT NULL
        REFERENCES ce_warehouse.c_series(series_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    tgt_cfreq TEXT[] NOT NULL
        CHECK (
            ARRAY_LENGTH(tgt_cfreq, 1) > 0
            AND tgt_cfreq <@ ARRAY['D', 'W', 'M', 'Q', 'Y']
        ),
    tgt_ifreq INT[] GENERATED ALWAYS AS (
        ce_warehouse.fx_ut_ifreq_multi(tgt_cfreq)
    ) STORED,

    src_series_id TEXT NOT NULL
        REFERENCES ce_warehouse.c_series(series_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    src_cfreq TEXT NOT NULL
        CHECK (src_cfreq IN ('D', 'W', 'M', 'Q', 'Y', '-')),
    src_ifreq INT GENERATED ALWAYS AS (
        ce_warehouse.fx_ut_ifreq_single(src_cfreq)
    ) STORED,

    formula_type TEXT NOT NULL
        CHECK (formula_type IN ('peop', 'psum', 'pmean', 'growth', 'growth-1')),

    internal_notes TEXT,  -- Unvalidated!

    regenerate BOOL NOT NULL DEFAULT TRUE,  -- Does this series need regenerating?

    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_api_calc),
    UNIQUE (tgt_series_id)
);

COMMENT ON TABLE ce_warehouse.c_api_calc
    IS 'Control table - "rules" for calculated values (AC-only)';
