/*
 ***********************************************************************************************************
 * @file
 * c_api_calc.sql
 *
 * Control table - "rules" for calculated values (AC-only).
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_api_calc;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_api_calc
(
    pk_api_calc INT GENERATED BY DEFAULT AS IDENTITY,
    ca_target_series TEXT NOT NULL
        REFERENCES ce_warehouse.c_series(s_series_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    ca_target_freq TEXT[] NOT NULL
        CHECK (
            ARRAY_LENGTH(ca_target_freq, 1) > 0
            AND ca_target_freq <@ ARRAY['D', 'W', 'M', 'Q', 'Y']
        ),
    ca_target_freq_int INT[] GENERATED ALWAYS AS (
        ce_warehouse.fx_ut_ifreq_multi(ca_target_freq)
    ) STORED,
    ca_source_series TEXT NOT NULL
        REFERENCES ce_warehouse.c_series(s_series_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    ca_source_freq TEXT NOT NULL
        CHECK (ca_source_freq IN ('D', 'W', 'M', 'Q', 'Y', '-')),
    ca_source_freq_int INT GENERATED ALWAYS AS (
        ce_warehouse.fx_ut_ifreq_single(ca_source_freq)
    ) STORED,
    ca_formula_type TEXT NOT NULL
        CHECK (ca_formula_type IN ('peop', 'psum', 'pmean', 'growth', 'growth-1')),

    internal_notes TEXT,  -- Internal notes, unvalidated!
    error TEXT,
    regenerate BOOLEAN NOT NULL DEFAULT TRUE,  -- Does this series need regenerating?
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (pk_api_calc),
    UNIQUE (ca_target_series)
);

COMMENT ON TABLE ce_warehouse.c_api_calc
    IS 'Control table - "rules" for calculated values (AC-only)';
