/*
 ***********************************************************************************************************
 * @file
 * c_calc_v2_v2.sql
 *
 * Control table - "rules" for calculated values (vers 2).
 * Handles both API calc & the more custom calculations, with the aim of simplifying logic & maintenance.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_calc_v2;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_calc_v2
(
    pk_calc INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    tgt_series_id TEXT NOT NULL
        REFERENCES ce_warehouse.c_series(series_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,
    tgt_cfreq TEXT NOT NULL
        CHECK (tgt_cfreq IN ('D', 'W', 'M', 'Q', 'Y')),
    tgt_type TEXT NOT NULL
        CHECK (tgt_type IN ('AC', 'F')),

    formula_type TEXT NOT NULL
        REFERENCES ce_warehouse.s_formula_type(code)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    formula TEXT NOT NULL,  -- Validated via APP

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes) IS NULL),

    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_calc),
    UNIQUE (tgt_series_id, tgt_cfreq, tgt_type)
);

COMMENT ON TABLE ce_warehouse.c_calc_v2
    IS 'Control table - "rules" for calculated values (vers 2)';
