/*
 ***********************************************************************************************************
 * @file
 * c_calc.sql
 *
 * Control table - "rules" for calculated values (AC/F/BLENDED).
 *
 * Initially the supported calculations will be:
 *
 * - simple calculations, e.g. #ABC_XYZ# * 2, multiple series can be specified
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_calc;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_calc
(
    pk_calc INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    series_id TEXT NOT NULL
        REFERENCES ce_warehouse.c_series(s_series_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,
    cfreq TEXT NOT NULL
        CHECK (cfreq IN ('D', 'W', 'M', 'Q', 'Y')),
    ctype TEXT NOT NULL
        CHECK (ctype IN ('AC', 'F', 'BLENDED')),

    -- Validated via APP, hence error column
    formula TEXT NOT NULL,

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes) IS NULL),

    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_calc),
    UNIQUE (series_id,  freq, type)
);

COMMENT ON TABLE ce_warehouse.c_calc
    IS 'Control table - "rules" for calculated values (AC/F/BLENDED)';
