/*
 ***********************************************************************************************************
 * @file
 * c_calc.sql
 *
 * Control table - "rules" for calculated values (AC/F/BLENDED).
 *
 * Initially the supported calculations will be:
 *
 * - simple calculations, e.g. #ABC_XYZ# * 2, multiple series can be specified
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_calc;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_calc
(
    pk_calc INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    calc_series TEXT NOT NULL
        REFERENCES ce_warehouse.c_series(s_series_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    calc_freq TEXT NOT NULL
        CHECK (calc_freq IN ('D', 'W', 'M', 'Q', 'Y')),
    calc_type TEXT NOT NULL
        CHECK (calc_type IN ('AC', 'F', 'BLENDED')),
    calc_formula TEXT NOT NULL,
    internal_notes TEXT,  -- Internal notes, unvalidated!
    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_calc),
    UNIQUE (calc_series,  calc_freq, calc_type)
);

COMMENT ON TABLE ce_warehouse.c_calc
    IS 'Control table - "rules" for calculated values (AC/F/BLENDED)';
