/*
 ***********************************************************************************************************
 * @file
 * c_com.sql
 *
 * Control table - commodity details, used for validation & extra detail.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_com;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_com
(
    pk_com INT GENERATED BY DEFAULT AS IDENTITY,
    com_code TEXT NOT NULL
        CHECK (com_code ~ '^C\.[A-Z0-9_]+[A-Z0-9]$' AND com_code !~ 'INTERNAL'),
    com_name TEXT NOT NULL,
    com_short_name TEXT NOT NULL,
    com_tla TEXT NOT NULL,
    com_type TEXT NOT NULL,  -- VALIDATION: via application, foreign key is too much of a pain
    com_order INT NOT NULL DEFAULT '0',
    internal_notes TEXT,  -- Internal notes, unvalidated!
    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY(pk_com),
    UNIQUE (com_code)
);

COMMENT ON TABLE ce_warehouse.c_com
      IS 'Control table - commodity details, used for validation & extra detail';
