/*
 ***********************************************************************************************************
 * @file
 * c_com.sql
 *
 * Control table - commodity details, used for validation & extra detail.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_com;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_com
(
    pk_com INT GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_com_code(code) IS NULL),
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(name) IS NULL),
    short_name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(short_name) IS NULL),
    tla TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(tla) IS NULL),
    commodity_type SMALLINT NOT NULL
        REFERENCES ce_warehouse.l_com_type(pk_com_type)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    ordering INT NOT NULL DEFAULT '0',

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes) IS NULL),

    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY(pk_com),
    UNIQUE (code)
);

-- It's recommended to have INDICES on foreign keys for performance!!
CREATE INDEX IF NOT EXISTS c_com__commodity_type__idx
    ON ce_warehouse.c_com (commodity_type);

COMMENT ON TABLE ce_warehouse.c_com
      IS 'Control table - commodity details, used for validation & extra detail';
