/*
 ***********************************************************************************************************
 * @file
 * c_const.sql
 *
 * Control table - constants lookup values, used in the assorted value calculations.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_const;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_const
(
    pk_con INT GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (code ~ '^[a-z][a-z0-9_]*[a-z0-9]$'),
    expr TEXT NOT NULL,  -- can also be a value
    value NUMERIC,  -- calculated value, can be NULL
    internal_notes TEXT,  -- Unvalidated!

    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_con),
    UNIQUE (code)
);

COMMENT ON TABLE ce_warehouse.c_const
    IS 'Control table - constants lookup values, used in the assorted value calculations';
