/*
 ***********************************************************************************************************
 * @file
 * c_com.sql
 *
 * Control table - commodity details, used for validation & extra detail.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_com;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_com
(
    pk_com INT GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (code ~ '^C\.[A-Z0-9_]+[A-Z0-9]$' AND code !~ 'INTERNAL'),
    name TEXT NOT NULL,
    short_name TEXT NOT NULL,
    tla TEXT NOT NULL,
    type TEXT NOT NULL,  -- VALIDATION: via application, foreign key is too much of a pain
    ordering INT NOT NULL DEFAULT '0',

    internal_notes TEXT,  -- Unvalidated!

    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY(pk_com),
    UNIQUE (code)
);

COMMENT ON TABLE ce_warehouse.c_com
      IS 'Control table - commodity details, used for validation & extra detail';
