/*
 ***********************************************************************************************************
 * @file
 * c_geo_group.sql
 *
 * Control table - GEO groups.
 * Replaces the "groups" array in c_geo with a more structured table, allowing for better maintenance.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_geo_group;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_geo_group
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_geo INT NOT NULL
        REFERENCES ce_warehouse.c_geo (pk_geo)
            DEFERRABLE INITIALLY DEFERRED
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    group_code TEXT NOT NULL
        REFERENCES ce_warehouse.l_geo_group (code)
            DEFERRABLE INITIALLY DEFERRED
            ON UPDATE CASCADE
            ON DELETE RESTRICT,

    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_geo, group_code)
);

COMMENT ON TABLE ce_warehouse.c_geo_group
    IS 'Control table - GEO groups';
