/*
 ***********************************************************************************************************
 * @file
 * c_geo.sql
 *
 * Control table - geography details, used for validation & extra detail.
 *
 * Originally just a lookup table, but due to its complexity it's been added to the control tables.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_geo;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_geo
(
    pk_geo INT GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_geo_code(code) IS NULL),
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(name) IS NULL),
    name2 TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(name2) IS NULL),
    short_name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(short_name) IS NULL),
    tla TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(tla) IS NULL),
    iso2 TEXT
        CHECK (iso2 ~ '^[A-Z]{2}$'),
    iso3 TEXT
        CHECK (iso3 ~ '^[A-Z]{3}$'),
    lat NUMERIC
        CHECK (lat >= -90 AND lat <= 90),
    long NUMERIC
        CHECK (long >= -180 AND long <= 180),
    central_bank SMALLINT
        REFERENCES ce_warehouse.l_central_bank(pk_central_bank)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,
    stock_market SMALLINT
        REFERENCES ce_warehouse.l_stock_market(pk_stock_market)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,
    political_alignment SMALLINT
        REFERENCES ce_warehouse.l_political_alignment(pk_political_alignment)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,
    local_currency_unit TEXT
        REFERENCES ce_warehouse.l_currency_unit(code)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,
    flag TEXT
        CHECK (ce_warehouse.fx_val_is_flag(flag) IS NULL),
    category SMALLINT NOT NULL
        REFERENCES ce_warehouse.l_geo_category(pk_geo_category)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,

    ordering INT NOT NULL DEFAULT 0,
    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes) IS NULL),

    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_geo),
    UNIQUE (code)
);

-- It's recommended to have INDICES on foreign keys for performance!! 
CREATE INDEX IF NOT EXISTS c_geo__central_bank__idx
    ON ce_warehouse.c_geo (central_bank);

CREATE INDEX IF NOT EXISTS c_geo__stock_market__idx
    ON ce_warehouse.c_geo (stock_market);

CREATE INDEX IF NOT EXISTS c_geo__political_alignment__idx
    ON ce_warehouse.c_geo (political_alignment);

CREATE INDEX IF NOT EXISTS c_geo__local_currency_unit__idx
    ON ce_warehouse.c_geo (local_currency_unit);

CREATE INDEX IF NOT EXISTS c_geo__category__idx
    ON ce_warehouse.c_geo (category);

COMMENT ON TABLE ce_warehouse.c_geo
    IS 'Control table - geography details, used for validation & extra detail';
