/*
 ***********************************************************************************************************
 * @file
 * c_geo_group.sql
 *
 * Control table - GEO groups.
 * Replaces the "groups" array in c_geo with a more structured table, allowing for better maintenance.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_geo_group;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_geo_group
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_geo INT NOT NULL
        REFERENCES ce_warehouse.c_geo (pk_geo)
            ON UPDATE CASCADE
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,

    group_code SMALLINT NOT NULL
        REFERENCES ce_warehouse.l_geo_group (pk_geo_group)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,

    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_geo, group_code)
);

COMMENT ON TABLE ce_warehouse.c_geo_group
    IS 'Control table - GEO groups';
