/*
 ***********************************************************************************************************
 * @file
 * c_geo.sql
 *
 * Control table - geography & commodity details, used for validation & extra detail.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_geo;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_geo
(
    pk_geo INT GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (code = 'INTERNAL' OR code ~ '^[GC]\.[A-Z][A-Z0-9_]*[A-Z0-9]$'),

    short_code TEXT NOT NULL GENERATED ALWAYS
        AS (SUBSTRING(code, 3)) STORED,
    geo_type TEXT NOT NULL GENERATED ALWAYS
        AS (
            CASE
                WHEN code LIKE 'G.%' THEN 'Geography'
                WHEN code LIKE 'C.%' THEN 'Commodity'
                WHEN code = 'INTERNAL' THEN 'Internal'
            END) STORED,

    -- Fields common to both GEO & COM
    name TEXT
        CHECK (
            (
                code <> 'INTERNAL'
                AND ce_warehouse.fx_val_is_name(name, 'c_geo.name', FALSE) IS NULL
            )
            OR (code = 'INTERNAL' AND name IS NULL)
    ),
    short_name TEXT
        CHECK (
            (
                code <> 'INTERNAL'
                AND ce_warehouse.fx_val_is_name(short_name, 'c_geo.short_name', FALSE) IS NULL
            )
            OR (code = 'INTERNAL' AND short_name IS NULL)
    ),
    tla TEXT
        CHECK (
            (
                code <> 'INTERNAL'
                AND ce_warehouse.fx_val_is_name(tla, 'c_geo.tla', FALSE) IS NULL
            )
            OR (code = 'INTERNAL' AND tla IS NULL)
    ),

    ordering INT NOT NULL DEFAULT 0,

    -- COM specific fields (will be NULL for GEO)
    commodity_type SMALLINT
        REFERENCES ce_warehouse.l_com_type(pk_com_type)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code LIKE 'C.%' AND commodity_type IS NOT NULL)
            OR (code NOT LIKE 'C.%' AND commodity_type IS NULL)
        ),

    -- GEO specific fields (will be NULL for COM)
    name2 TEXT
        CHECK (
            (code NOT LIKE 'G.%' AND name2 IS NULL)
            OR (
                code LIKE 'G.%'
                AND ce_warehouse.fx_val_is_name(name2, 'c_geo.name2', FALSE) IS NULL
            )
    ),
    iso2 TEXT
        CHECK (
            (code NOT LIKE 'G.%' AND iso2 IS NULL)
            OR (code LIKE 'G.%' AND (iso2 IS NULL OR iso2 ~ '^[A-Z]{2}$'))
    ),
    iso3 TEXT
        CHECK (
            (code NOT LIKE 'G.%' AND iso3 IS NULL)
            OR (code LIKE 'G.%' AND (iso3 IS NULL OR iso2 ~ '^[A-Z]{3}$'))
    ),
    lat NUMERIC
        CHECK (
            (code NOT LIKE 'G.%' AND lat IS NULL)
            OR (code LIKE 'G.%' AND (lat IS NULL OR lat BETWEEN -90 AND 90))
    ),
    long NUMERIC
        CHECK (
            (code NOT LIKE 'G.%' AND long IS NULL)
            OR (code LIKE 'G.%' AND (long IS NULL OR long BETWEEN -180 AND 180))
    ),
    central_bank SMALLINT
        REFERENCES ce_warehouse.l_central_bank(pk_central_bank)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code NOT LIKE 'G.%' AND central_bank IS NULL)
            OR code LIKE 'G.%'
    ),
    stock_market SMALLINT
        REFERENCES ce_warehouse.l_stock_market(pk_stock_market)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code NOT LIKE 'G.%' AND stock_market IS NULL)
            OR code LIKE 'G.%'
    ),
    political_alignment SMALLINT
        REFERENCES ce_warehouse.l_political_alignment(pk_political_alignment)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code NOT LIKE 'G.%' AND political_alignment IS NULL)
            OR code LIKE 'G.%'
    ),
    local_currency_unit TEXT
        REFERENCES ce_warehouse.l_currency_unit(code)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            (code NOT LIKE 'G.%' AND local_currency_unit IS NULL)
            OR code LIKE 'G.%'
    ),
    flag TEXT
        CHECK (
                (code NOT LIKE 'G.%' AND flag IS NULL)
                OR (code LIKE 'G.%' AND ce_warehouse.fx_val_is_flag(flag) IS NULL)
    ),
    category SMALLINT
        REFERENCES ce_warehouse.l_geo_category(pk_geo_category)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
                (code NOT LIKE 'G.%' AND category IS NULL)
                OR (code LIKE 'G.%' AND category IS NOT NULL)
    ),

    -- Standard fields
    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes, 'internal_notes') IS NULL),

    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_geo),
    UNIQUE (code),
    UNIQUE (short_code)
);

-- It's recommended to have INDICES on foreign keys for performance!!
CREATE INDEX IF NOT EXISTS c_geo__commodity_type__idx
    ON ce_warehouse.c_geo (commodity_type);

CREATE INDEX IF NOT EXISTS c_geo__central_bank__idx
    ON ce_warehouse.c_geo (central_bank);

CREATE INDEX IF NOT EXISTS c_geo__stock_market__idx
    ON ce_warehouse.c_geo (stock_market);

CREATE INDEX IF NOT EXISTS c_geo__political_alignment__idx
    ON ce_warehouse.c_geo (political_alignment);

CREATE INDEX IF NOT EXISTS c_geo__local_currency_unit__idx
    ON ce_warehouse.c_geo (local_currency_unit);

CREATE INDEX IF NOT EXISTS c_geo__category__idx
    ON ce_warehouse.c_geo (category);

COMMENT ON TABLE ce_warehouse.c_geo
    IS 'Control table - geography details, used for validation & extra detail';
