/*
 ***********************************************************************************************************
 * @file
 * c_geo.sql
 *
 * Control table - geography details, used for validation & extra detail.
 *
 * Originally just a lookup table, but due to its complexity it's been added to the control tables.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_geo;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_geo
(
    pk_geo INT GENERATED BY DEFAULT AS IDENTITY,
    geo_code TEXT NOT NULL
        CHECK (geo_code ~ '^G\.[A-Z0-9_]+[A-Z0-9]$' AND geo_code !~ 'INTERNAL'),
    geo_name TEXT NOT NULL,
    geo_name2 TEXT NOT NULL,
    geo_short_name TEXT NOT NULL,
    geo_tla TEXT NOT NULL,
    geo_iso2 TEXT,
    geo_iso3 TEXT,
    geo_lat NUMERIC,
    geo_long NUMERIC,
    geo_cb TEXT,
    geo_cb_short TEXT,
    geo_stockmarket TEXT,
    geo_stockmarket_short TEXT,
    geo_political_alignment TEXT,  -- VALIDATION: via application, foreign key is too much of a pain
    geo_lc TEXT,
    geo_lcu TEXT,
    geo_flag TEXT,
    geo_catg TEXT NOT NULL,  -- VALIDATION: via application, foreign key is too much of a pain
    geo_groups TEXT[],
    geo_order INT NOT NULL DEFAULT 0,
    internal_notes TEXT,  -- Internal notes, unvalidated!
    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (pk_geo),
    UNIQUE (geo_code)
);

COMMENT ON TABLE ce_warehouse.c_geo
    IS 'Control table - geography details, used for validation & extra detail';
