/*
 ***********************************************************************************************************
 * @file
 * c_geo_group.sql
 *
 * Control table - GEO groups.
 * Replaces the "groups" array in c_geo with a more structured table, allowing for better maintenance.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_geo_group;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_geo_group
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_geo INT NOT NULL
        REFERENCES ce_warehouse.c_geo (pk_geo)
            ON UPDATE CASCADE
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,

    -- GEO Group ID
    geo_group SMALLINT NOT NULL
        REFERENCES ce_warehouse.l_geo_group (pk_geo_group)
            ON UPDATE CASCADE
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,

    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_geo, geo_group)
);

-- It's recommended to have INDICES on foreign keys for performance!!
-- unless we already have them on the referenced table
CREATE INDEX IF NOT EXISTS c_geo_group__geo_group__idx
    ON ce_warehouse.c_geo_group (geo_group);

COMMENT ON TABLE ce_warehouse.c_geo_group
    IS 'Control table - GEO groups';
