/*
 ***********************************************************************************************************
 * @file
 * c_ind.sql
 *
 * Control table - indicator details, used for validation & lookup.
 *
 * Defined as a control table because it's details pass into PowerBi schema.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_ind;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_ind
(
    pk_i INT GENERATED BY DEFAULT AS IDENTITY,
    
    code TEXT NOT NULL
        CHECK (code ~ '^[A-Z0-9][A-Z0-9<>._\-+#£$%]*[A-Z0-9#£€$%]$'),
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_text(name)),
    description TEXT,
    name1 TEXT,
    name2 TEXT,
    name3 TEXT,
    name4 TEXT,
    name_lower TEXT,
    name1_lower TEXT,
    name2_lower TEXT,
    name3_lower TEXT,
    name4_lower TEXT,
    catg_broad TEXT,
    catg_narrow TEXT,
    parent_icodes TEXT[],
    data_transformation TEXT NOT NULL
        REFERENCES ce_warehouse.l_data_transformation (code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    keyindicator BOOL NOT NULL DEFAULT FALSE,
    proprietary_data BOOL NOT NULL DEFAULT FALSE,
    ordering INT NOT NULL DEFAULT 0,

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes)),
    
    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_i),
    UNIQUE (code)
);
CREATE TABLE IF NOT EXISTS ce_warehouse.c_ind
(
    pk_i INT GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (code ~ '^[A-Z0-9][A-Z0-9<>._\-+#£$%]*[A-Z0-9#£€$%]$'),
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_text(name)),
    description TEXT
        CHECK (ce_warehouse.fx_val_is_text(description)),
    name1 TEXT
        CHECK (ce_warehouse.fx_val_is_text(name1)),
    name2 TEXT
        CHECK (ce_warehouse.fx_val_is_text(name2)),
    name3 TEXT
        CHECK (ce_warehouse.fx_val_is_text(name3)),
    name4 TEXT
        CHECK (ce_warehouse.fx_val_is_text(name4)),
    name_lower TEXT
        CHECK (ce_warehouse.fx_val_is_text(name_lower)),
    name1_lower TEXT
        CHECK (ce_warehouse.fx_val_is_text(name1_lower)),
    name2_lower TEXT
        CHECK (ce_warehouse.fx_val_is_text(name2_lower)),
    name3_lower TEXT
        CHECK (ce_warehouse.fx_val_is_text(name3_lower)),
    name4_lower TEXT
        CHECK (ce_warehouse.fx_val_is_text(name4_lower)),
    catg_broad TEXT
        CHECK (ce_warehouse.fx_val_is_text(catg_broad)),
    catg_narrow TEXT
        CHECK (ce_warehouse.fx_val_is_text(catg_narrow)),
    -- validated via APP, hence error column
    parent_icodes TEXT[],
    data_transformation TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_text(data_transformation))
        REFERENCES ce_warehouse.l_data_transformation (code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    keyindicator BOOL NOT NULL DEFAULT FALSE,
    proprietary_data BOOL NOT NULL DEFAULT FALSE,
    ordering INT NOT NULL DEFAULT 0,

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes)),

    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_i),
    UNIQUE (code)
);

COMMENT ON TABLE ce_warehouse.c_ind
    IS 'Control table - indicator details, used for validation & lookup';
