/*
 ***********************************************************************************************************
 * @file
 * c_ind.sql
 *
 * Control table - indicator details, used for validation & lookup.
 *
 * Defined as a control table because it's details pass into PowerBi schema.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_ind;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_ind
(
    pk_ind INT GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (code ~ '^[A-Z0-9][A-Z0-9<>._\-+#%£$]*[A-Z0-9#%£$€]$'),
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(name) IS NULL),
    description TEXT
        CHECK (ce_warehouse.fx_val_is_name(description) IS NULL),
    name1 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name1) IS NULL),
    name2 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name2) IS NULL),
    name3 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name3) IS NULL),
    name4 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name4) IS NULL),
    name_lower TEXT
        CHECK (ce_warehouse.fx_val_is_name(name_lower) IS NULL),
    name1_lower TEXT
        CHECK (ce_warehouse.fx_val_is_name(name1_lower) IS NULL),
    name2_lower TEXT
        CHECK (ce_warehouse.fx_val_is_name(name2_lower) IS NULL),
    name3_lower TEXT
        CHECK (ce_warehouse.fx_val_is_name(name3_lower) IS NULL),
    name4_lower TEXT
        CHECK (ce_warehouse.fx_val_is_name(name4_lower) IS NULL),
    catg_broad TEXT
        REFERENCES ce_warehouse.l_ind_broad_category (name)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    catg_narrow TEXT
        REFERENCES ce_warehouse.l_ind_narrow_category (name)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    data_transformation TEXT NOT NULL
        REFERENCES ce_warehouse.l_data_transformation (code)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    keyindicator BOOL NOT NULL DEFAULT FALSE,
    proprietary_data BOOL NOT NULL DEFAULT FALSE,
    ordering INT NOT NULL DEFAULT 0,

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes) IS NULL),

    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_ind),
    UNIQUE (code)
);

COMMENT ON TABLE ce_warehouse.c_ind
    IS 'Control table - indicator details, used for validation & lookup';

/*
 ***********************************************************************************************************
 * Trigger to update affected IND records when an indicater code is updated or deleted.
 ***********************************************************************************************************
 */

-- @todo
