/*
 ***********************************************************************************************************
 * @file
 * c_ind_parent.sql
 *
 * Control table - IND parents.
 * Replaces the "parent_icodes" array in c_ind with a more structured table, allowing for better maintenance.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_ind_parent;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_ind_parent
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_ind INT NOT NULL
        REFERENCES ce_warehouse.c_ind (pk_ind)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,

    fk_pk_ind__parent INT NOT NULL
        REFERENCES ce_warehouse.c_ind (pk_ind)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED
        CHECK (
            fk_pk_ind > 0
            AND fk_pk_ind__parent > 0
            AND fk_pk_ind__parent <> fk_pk_ind  -- prevent self-reference
        ),

    error TEXT,  -- system generated
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_ind, fk_pk_ind__parent)
);

-- It's recommended to have INDICES on foreign keys for performance!!
-- unless we already have them on the referenced table
CREATE INDEX IF NOT EXISTS c_ind__parent__idx
    ON ce_warehouse.c_ind_parent (fk_pk_ind__parent);

COMMENT ON TABLE ce_warehouse.c_ind_parent
    IS 'Control table - IND parents';
