/*
 ***********************************************************************************************************
 * @file
 * c_ind_parent.sql
 *
 * Control table - IND parents.
 * Replaces the "parent_icodes" array in c_ind with a more structured table, allowing for better maintenance.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_ind_parent;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_ind_parent
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_i INT NOT NULL
        REFERENCES ce_warehouse.c_ind (pk_i)
            DEFERRABLE INITIALLY DEFERRED
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    icode TEXT NOT NULL
        REFERENCES ce_warehouse.c_ind (code)
            DEFERRABLE INITIALLY DEFERRED
            ON UPDATE CASCADE
            ON DELETE RESTRICT,

    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_geo, icode)
);

COMMENT ON TABLE ce_warehouse.c_ind_parent
    IS 'Control table - IND parents';
