/*
 ***********************************************************************************************************
 * @file
 * c_series.sql
 *
 * Control table - series definition, lookup/validation.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_series;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_series
(
    pk_s INT GENERATED BY DEFAULT AS IDENTITY,
    s_gcode TEXT NOT NULL,
    s_icode TEXT NOT NULL,
    s_series_id TEXT GENERATED ALWAYS
        AS (s_gcode || '_' || s_icode) STORED,  -- Series code
    s_name TEXT NOT NULL,
    s_name1 TEXT,
    s_name2 TEXT,
    s_name3 TEXT,
    s_name4 TEXT,
    s_description TEXT,
    s_source TEXT,
    s_units TEXT,
    s_precision INT NOT NULL,
    s_date_point TEXT NOT NULL DEFAULT 'mid',
    s_active BOOL NOT NULL DEFAULT TRUE,
    s_order INT NOT NULL DEFAULT 0,
    is_internal BOOLEAN NOT NULL GENERATED ALWAYS
        AS (s_gcode = 'INTERNAL') STORED,  -- flag to indicate if INTERNAL series
    internal_notes TEXT,  -- Internal notes, unvalidated!
    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (pk_s),
    UNIQUE (s_gcode, s_icode),
    UNIQUE (s_series_id)
);

COMMENT ON TABLE ce_warehouse.c_series
    IS 'Control table - series definition, lookup/validation';
