/*
 ***********************************************************************************************************
 * @file
 * c_series.sql
 *
 * Control table - series definition, lookup/validation.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_series;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_series
(
    pk_series INT GENERATED BY DEFAULT AS IDENTITY,

    gcode TEXT NOT NULL
        CHECK (
            gcode = 'INTERNAL' OR
            ce_warehouse.fx_val_is_geo_code(gcode, FALSE) IS NULL
        ),
    icode TEXT NOT NULL
        REFERENCES ce_warehouse.c_ind (code)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,

    -- Auto generated ID-based fields
    series_id TEXT GENERATED ALWAYS
        AS (gcode || '_' || icode) STORED,  -- Series code
    sid1 TEXT GENERATED ALWAYS
        AS (
            CASE WHEN gcode = 'INTERNAL' THEN gcode || '_' || icode
            ELSE SUBSTR(gcode, 3) || '_' || icode
            END
        ) STORED,
    is_internal BOOL NOT NULL GENERATED ALWAYS
        AS (gcode = 'INTERNAL') STORED,

    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(name, 'c_series.name', FALSE) IS NULL),
    name1 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name1, 'c_series.name1') IS NULL),
    name2 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name2, 'c_series.name2') IS NULL),
    name3 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name3, 'c_series.name3') IS NULL),
    name4 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name4, 'c_series.name4') IS NULL),
    description TEXT
        CHECK (ce_warehouse.fx_val_is_name(description, 'c_series.description') IS NULL),
    units SMALLINT
        REFERENCES ce_warehouse.l_units (pk_units)
            ON UPDATE CASCADE
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,
    precision INT NOT NULL
        CHECK (precision BETWEEN -1 AND 12),  -- number of decimal places for rounding in PowerBI
    date_point TEXT NOT NULL DEFAULT 'mid'
        CHECK (date_point IN ('start', 'mid', 'end')),  -- where to place the date point for the period in PowerBI
    active BOOL NOT NULL DEFAULT TRUE,
    ordering INT NOT NULL DEFAULT 0,

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes, 'internal_notes') IS NULL),

    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_series),
    UNIQUE(pk_series, sid1),  -- enforce unique SID1 per series, for the FK in x_series_meta
    UNIQUE (series_id),
    UNIQUE (sid1)
);

-- It's recommended to have INDICES on foreign keys for performance!!
CREATE INDEX IF NOT EXISTS c_series__icode__idx
    ON ce_warehouse.c_series (icode);

CREATE INDEX IF NOT EXISTS c_series__units__idx
    ON ce_warehouse.c_series (units);

COMMENT ON TABLE ce_warehouse.c_series
    IS 'Control table - series definition, lookup/validation';
