/*
 ***********************************************************************************************************
 * @file
 * c_series.sql
 *
 * Control table - series definition, lookup/validation.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_series;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_series
(
    pk_series INT GENERATED BY DEFAULT AS IDENTITY,

    gcode TEXT NOT NULL
        CHECK (
            gcode = 'INTERNAL' OR
            ce_warehouse.fx_val_is_geo_or_com(gcode, FALSE) IS NULL
        ),
    icode TEXT NOT NULL
        REFERENCES ce_warehouse.c_ind (code)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,

    -- Auto generated fields
    series_id TEXT GENERATED ALWAYS
        AS (gcode || '_' || icode) STORED,  -- Series code
    sid1 TEXT GENERATED ALWAYS
        AS (
            CASE WHEN gcode = 'INTERNAL' THEN gcode || '_' || icode
            ELSE SUBSTR(gcode, 3) || '_' || icode
        ) STORED,
    is_internal BOOL NOT NULL GENERATED ALWAYS
        AS (gcode = 'INTERNAL') STORED,

    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(name) IS NULL),
    name1 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name1) IS NULL),
    name2 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name2) IS NULL),
    name3 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name3) IS NULL),
    name4 TEXT
        CHECK (ce_warehouse.fx_val_is_name(name4) IS NULL),
    description TEXT
        CHECK (ce_warehouse.fx_val_is_name(description) IS NULL),
    data_source TEXT
        CHECK (ce_warehouse.fx_val_is_name(data_source) IS NULL),
    units TEXT
        REFERENCES ce_warehouse.l_units (code)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    precision INT NOT NULL
        CHECK (precision BETWEEN -1 AND 12),  -- number of decimal places for rounding in PowerBI
    date_point TEXT NOT NULL DEFAULT 'mid'
        CHECK (date_point IN ('start', 'mid', 'end')),  -- where to place the date point for the period in PowerBI
    active BOOL NOT NULL DEFAULT TRUE,
    ordering INT NOT NULL DEFAULT 0,

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val_is_text(internal_notes) IS NULL),

    error TEXT,
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_series),
    UNIQUE (series_id),
    UNIQUE (sid1)
);

COMMENT ON TABLE ce_warehouse.c_series
    IS 'Control table - series definition, lookup/validation';
