/*
 ***********************************************************************************************************
 * @file
 * c_series_downloadable.sql
 *
 * Control table - series downloadable flags etc.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.c_series_downloadable;

CREATE TABLE IF NOT EXISTS ce_warehouse.c_series_downloadable
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_series INT NOT NULL
        REFERENCES ce_warehouse.c_series (pk_series)
            ON UPDATE CASCADE
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED,
    ifreq SMALLINT NOT NULL
        CHECK (ifreq IN (1, 2, 3, 4, 5)),
    itype SMALLINT NOT NULL,
        CHECK (itype IN (1, 2)),

    -- User maintained fields
    downloadable TEXT NOT NULL DEFAULT 'ess_plugin'
        CHECK (downloadable IN ('all', 'api', 'adv_plugin', 'ess_plugin', 'internal', 'none', 'powerbi')),  -- control which series are downloadable and via which channels
    forecast_only_lifespan INT,  -- If NULL then will take the system default
    internal_notes TEXT,  -- Unvalidated!

    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_series, ifreq, itype)
);

COMMENT ON TABLE ce_warehouse.c_series_downloadable
    IS 'Control table - series downloadable flags etc';
