/*
 ***********************************************************************************************************
 * @file
 * l__user.sql
 *
 * Lookup table - provides a link to app users for auditing and other purposes. System generated.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l__user;

CREATE TABLE IF NOT EXISTS ce_warehouse.l__user
(
    pk_user INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    name TEXT NOT NULL
        CHECK (name <> ''),  -- Ensure that the name is not empty
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive', 'deleted')),
    source_uid INT NOT NULL,  -- Store the source user ID from the application, for reference

    -- Additional cutom fields
    is_admin BOOL NOT NULL DEFAULT FALSE,  -- Admin user
    is_data_team BOOL NOT NULL DEFAULT FALSE,  -- Member of the data team
    is_value_uploader BOOL NOT NULL DEFAULT FALSE,  -- User with financial upload permissions
    is_checking_required BOOL NOT NULL DEFAULT FALSE,  -- User value uploads require "checking"

    internal_notes TEXT
        CHECK (ce_warehouse.fx_val__is_text(internal_notes, 'internal_notes') IS NULL),

    ts_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (pk_user),
    UNIQUE (source_uid)
);

COMMENT ON TABLE ce_warehouse.l__user
    IS 'Lookup table - (series) units lookup';

/**
 * Pre-populate with System Use values.
 */
INSERT INTO ce_warehouse.l__user (pk_user, name, source_uid, internal_notes)
VALUES
    (-1, 'migration', -1, 'System user for data migration and backfilling'),
    (-2, 'app', -2, 'System user for automated processes');

/*
 ***********************************************************************************************************
 * Block any updates to system records
 ***********************************************************************************************************
 */

-- DROP TRIGGER IF EXISTS tg__luser__b01 ON ce_warehouse.l__user;

CREATE TRIGGER tg__luser__b01
    BEFORE UPDATE OR DELETE
        ON ce_warehouse.l__user
    FOR EACH ROW
        EXECUTE FUNCTION ce_warehouse.fx_tg__utils__block_internal('pk_user');

COMMENT ON TRIGGER tg__luser__b01 ON ce_warehouse.l__user
    IS 'Trigger to block changes to system records on l__user table';
