/*
 ***********************************************************************************************************
 * @file
 * l_central_bank.sql
 *
 * Lookup table - central bank lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_central_bank;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_central_bank
(
    code TEXT NOT NULL
        CHECK (code ~ '^[A-Z][A-Za-z0-9 ]*$'),
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_text(name)),

    PRIMARY KEY (code),
    UNIQUE (name)
);

COMMENT ON TABLE ce_warehouse.l_central_bank
    IS 'Lookup table - central bank lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_central_bank (code, name)
VALUES
    ('AMBD', 'Autoriti Monetari Brunei Darussalam'),
    ('AMCM', 'Monetary Authority of Macao'),
    ('BA', 'Bank of Algeria'),
    ('BANGUAT', 'Bank of Guatemala'),
    ('BANXICO', 'Bank of Mexico'),
    ('BB', 'Bangladesh Bank'),
    ('BCB', 'Central Bank of Brazil'),
    ('BCB', 'Central Bank of Bolivia'),
    ('BCC', 'Central Bank of Congo'),
    ('BCC', 'Central Bank of Cuba'),
    ('BCC', 'Central Bank of Comoros'),
    ('BCC', 'Central Bank of Chile'),
    ('BCCR', 'Central Bank of Costa Rica'),
    ('BCD', 'Central Bank of Djibouti'),
    ('BCE', 'Central Bank of Ecuador'),
    ('BCEAO', 'Central Bank of West African States'),
    ('BCH', 'Central Bank of Honduras'),
    ('BCL', 'Central Bank of Luxembourg'),
    ('BCM', 'Central Bank of Mauritania'),
    ('BCM', 'Central Bank of Madagascar'),
    ('BCN', 'Central Bank of Nicaragua'),
    ('BCP', 'Central Bank of Paraguay'),
    ('BCRA', 'Central Bank of Argentina'),
    ('BCRD', 'Central Bank of the Dominican Republic'),
    ('BCRES', 'Central Reserve Bank of El Salvador'),
    ('BCRG', 'Central Bank of the Republic of Guinea'),
    ('BCRP', 'Central Reserve Bank of Peru'),
    ('BCSTP', 'Central Bank of Sao Tome and Principe'),
    ('BCT', 'Central Bank of Tunisia'),
    ('BCTL', 'Central Bank of Timor-Leste'),
    ('BCU', 'Central Bank of Uruguay'),
    ('BCV', 'Central Bank of Venezuela'),
    ('BDL', 'Banque du Liban'),
    ('BdP', 'Bank of Portugal'),
    ('BdR', 'Bank of the Republic'),
    ('BEAC', 'Bank of Central African States'),
    ('BI', 'Bank Indonesia'),
    ('BM', 'Bank of Mozambique'),
    ('BMA', 'Bermuda Monetary Authority'),
    ('BNA', 'National Bank of Angola'),
    ('BNB', 'Bulgarian National Bank'),
    ('BNM', 'Bank of Morocco'),
    ('BNM', 'Central Bank of Malaysia'),
    ('BNP', 'National Bank of Panama'),
    ('BNR', 'National Bank of Rwanda'),
    ('BNR', 'National Bank of Romania'),
    ('BoA', 'Bank of Albania'),
    ('BoB', 'Bank of Botswana'),
    ('BoC', 'Bank of Canada'),
    ('BoE', 'Bank of England'),
    ('BoF', 'Bank of Finland'),
    ('BoG', 'Bank of Ghana'),
    ('BoG', 'Bank of Guyana'),
    ('BoG', 'Bank of Greece'),
    ('BoI', 'Bank of Italy'),
    ('BoI', 'Bank of Israel'),
    ('BOJ', 'Bank of Japan'),
    ('BOJ', 'Bank of Jamaica'),
    ('BOK', 'Bank of Korea'),
    ('BOL', 'Bank of Lithuania'),
    ('BOL', 'Bank of the Lao PDR'),
    ('BOM', 'Bank of Mauritius'),
    ('BOM', 'Bank of Mongolia'),
    ('BoN', 'Bank of Namibia'),
    ('BoS', 'Bank of Spain'),
    ('BOSS', 'Bank of South Sudan'),
    ('BOT', 'Bank of Tanzania'),
    ('BOT', 'Bank of Thailand'),
    ('BOU', 'Bank of Uganda'),
    ('BoZ', 'Bank of Zambia'),
    ('BPNG', 'Bank of Papua New Guinea'),
    ('BRB', 'Bank of the Republic of Burundi'),
    ('BRH', 'Bank of the Republic of Haiti'),
    ('BSI', 'Bank of Slovenia'),
    ('BSL', 'Bank of Sierra Leone'),
    ('BSP', 'Bangko Sentral ng Pilipinas'),
    ('Bundesbank', 'Deutsche Bundesbank'),
    ('BVC', 'Bank of Cape Verde'),
    ('CB', 'Central Bank of Uzbekistan'),
    ('CB', 'Central Bank of the Democratic People''s Republic of Korea'),
    ('CBA', 'Central Bank of Armenia'),
    ('CBA', 'Central Bank of Aruba'),
    ('CBA', 'Central Bank of Azerbaijan'),
    ('CBB', 'Central Bank of Bahrain'),
    ('CBB', 'Central Bank of Barbados'),
    ('CBB', 'Central Bank of Belize'),
    ('CBBH', 'Central Bank of Bosnia and Herzegovina'),
    ('CBC', 'Central Bank of the Republic of China'),
    ('CBC', 'Central Bank of Cyprus'),
    ('CBCG', 'Central Bank of Montenegro'),
    ('CBCS', 'Central Bank of Curacao and Sint Maarten'),
    ('CBE', 'Central Bank of Egypt'),
    ('CBG', 'Central Bank of The Gambia'),
    ('CBI', 'Central Bank of Ireland'),
    ('CBI', 'Central Bank of Iran'),
    ('CBI', 'Central Bank of Iceland'),
    ('CBI', 'Central Bank of Iraq'),
    ('CBJ', 'Central Bank of Jordan'),
    ('CBK', 'Central Bank of Kenya'),
    ('CBK', 'Central Bank of Kuwait'),
    ('CBK', 'Central Bank of the Republic of Kosovo'),
    ('CBL', 'Central Bank of Lesotho'),
    ('CBL', 'Central Bank of Liberia'),
    ('CBL', 'Central Bank of Libya'),
    ('CBM', 'Central Bank of Myanmar'),
    ('CBM', 'Central Bank of Malta'),
    ('CBN', 'Central Bank of Nigeria'),
    ('CBO', 'Central Bank of Oman'),
    ('CBOB', 'Central Bank of The Bahamas'),
    ('CBOS', 'Central Bank of Sudan'),
    ('CBR', 'Central Bank of Russia'),
    ('CBRT', 'Central Bank of Turkmenistan'),
    ('CBRT', 'Central Bank of the Republic of Turkey'),
    ('CBS', 'Central Bank of Samoa'),
    ('CBS', 'Central Bank of Seychelles'),
    ('CBS', 'Central Bank of Eswatini'),
    ('CBS', 'Central Bank of Syria'),
    ('CBS', 'Central Bank of Somalia'),
    ('CBSI', 'Central Bank of Solomon Islands'),
    ('CBSL', 'Central Bank of Sri Lanka'),
    ('CBSM', 'Central Bank of the Republic of San Marino'),
    ('CBTT', 'Central Bank of Trinidad and Tobago'),
    ('CBUAE', 'Central Bank of the UAE'),
    ('CBvS', 'Central Bank of Suriname'),
    ('CBY', 'Central Bank of Yemen'),
    ('CIMA', 'Cayman Islands Monetary Authority'),
    ('CNB', 'Czech National Bank'),
    ('DAB', 'Da Afghanistan Bank'),
    ('DN', 'Danmarks Nationalbank'),
    ('DNB', 'De Nederlandsche Bank'),
    ('ECB', 'European Central Bank'),
    ('ECCB', 'Eastern Caribbean Central Bank'),
    ('EKP', 'Eesti Pank'),
    ('FRB', 'Federal Reserve System'),
    ('FRBNY', 'Federal Reserve Bank of NY'),
    ('Government of Gibraltar', 'Government of Gibraltar'),
    ('HKMA', 'Hong Kong Monetary Authority'),
    ('HNB', 'Croatian National Bank'),
    ('Isle of Man Government', 'Isle of Man Government'),
    ('JFSC', 'Jersey Financial Services Commission'),
    ('LB', 'Latvijas Banka'),
    ('LLB', 'Liechtensteinische Landesbank'),
    ('MAS', 'Monetary Authority of Singapore'),
    ('MMA', 'Maldives Monetary Authority'),
    ('MNB', 'Magyar Nemzeti Bank'),
    ('NB', 'Norges Bank'),
    ('NBB', 'National Bank of Belgium'),
    ('NBC', 'National Bank of Cambodia'),
    ('NBE', 'National Bank of Ethiopia'),
    ('NBG', 'National Bank of Georgia'),
    ('NBK', 'National Bank of Kazakhstan'),
    ('NBKR', 'National Bank of the Kyrgyz Republic'),
    ('NBM', 'National Bank of Moldova'),
    ('NBP', 'National Bank of Poland'),
    ('NBRB', 'National Bank of the Republic of Belarus'),
    ('NBRM', 'National Bank of the Republic of North Macedonia'),
    ('NBS', 'National Bank of Serbia'),
    ('NBS', 'National Bank of Slovakia'),
    ('NBT', 'National Bank of Tajikistan'),
    ('NBU', 'National Bank of Ukraine'),
    ('NRB', 'Nepal Rastra Bank'),
    ('NRBT', 'National Reserve Bank of Tonga'),
    ('OeNB', 'Austrian National Bank'),
    ('PBOC', 'People''s Bank of China'),
    ('PMA', 'Palestine Monetary Authority'),
    ('QCB', 'Qatar Central Bank'),
    ('RBA', 'Reserve Bank of Australia'),
    ('RBF', 'Reserve Bank of Fiji'),
    ('RBI', 'Reserve Bank of India'),
    ('RBM', 'Reserve Bank of Malawi'),
    ('RBNZ', 'Reserve Bank of New Zealand'),
    ('RBV', 'Reserve Bank of Vanuatu'),
    ('RBZ', 'Reserve Bank of Zimbabwe'),
    ('RMA', 'Royal Monetary Authority of Bhutan'),
    ('SAMA', 'Saudi Arabian Monetary Authority'),
    ('SARB', 'South African Reserve Bank'),
    ('SBP', 'State Bank of Pakistan'),
    ('SBV', 'State Bank of Vietnam'),
    ('SNB', 'Swiss National Bank'),
    ('Sveriges Riksbank', 'Sveriges Riksbank'),
    ('VB', 'Vatican Bank');
