/*
 ***********************************************************************************************************
 * @file
 * l_central_bank.sql
 *
 * Lookup table - central bank lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_central_bank;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_central_bank
(
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(name) IS NULL),
    short_code TEXT NOT NULL
        CHECK (short_code ~ '^[A-Z][A-Za-z0-9 ]*$'),

    PRIMARY KEY (name)
);

COMMENT ON TABLE ce_warehouse.l_central_bank
    IS 'Lookup table - central bank lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_central_bank (name, short_code)
VALUES
    ('Austrian National Bank', 'OeNB'),
    ('Autoriti Monetari Brunei Darussalam', 'AMBD'),
    ('Bangko Sentral ng Pilipinas', 'BSP'),
    ('Bangladesh Bank', 'BB'),
    ('Bank Indonesia', 'BI'),
    ('Bank of Albania', 'BoA'),
    ('Bank of Algeria', 'BA'),
    ('Bank of Botswana', 'BoB'),
    ('Bank of Canada', 'BoC'),
    ('Bank of Cape Verde', 'BVC'),
    ('Bank of Central African States', 'BEAC'),
    ('Bank of England', 'BoE'),
    ('Bank of Finland', 'BoF'),
    ('Bank of Ghana', 'BoG'),
    ('Bank of Greece', 'BoG'),
    ('Bank of Guatemala', 'BANGUAT'),
    ('Bank of Guyana', 'BoG'),
    ('Bank of Israel', 'BoI'),
    ('Bank of Italy', 'BoI'),
    ('Bank of Jamaica', 'BOJ'),
    ('Bank of Japan', 'BOJ'),
    ('Bank of Korea', 'BOK'),
    ('Bank of Lithuania', 'BOL'),
    ('Bank of Mauritius', 'BOM'),
    ('Bank of Mexico', 'BANXICO'),
    ('Bank of Mongolia', 'BOM'),
    ('Bank of Morocco', 'BNM'),
    ('Bank of Mozambique', 'BM'),
    ('Bank of Namibia', 'BoN'),
    ('Bank of Papua New Guinea', 'BPNG'),
    ('Bank of Portugal', 'BdP'),
    ('Bank of Sierra Leone', 'BSL'),
    ('Bank of Slovenia', 'BSI'),
    ('Bank of South Sudan', 'BOSS'),
    ('Bank of Spain', 'BoS'),
    ('Bank of Tanzania', 'BOT'),
    ('Bank of Thailand', 'BOT'),
    ('Bank of the Lao PDR', 'BOL'),
    ('Bank of the Republic', 'BdR'),
    ('Bank of the Republic of Burundi', 'BRB'),
    ('Bank of the Republic of Haiti', 'BRH'),
    ('Bank of Uganda', 'BOU'),
    ('Bank of Zambia', 'BoZ'),
    ('Banque du Liban', 'BDL'),
    ('Bermuda Monetary Authority', 'BMA'),
    ('Bulgarian National Bank', 'BNB'),
    ('Cayman Islands Monetary Authority', 'CIMA'),
    ('Central Bank of Argentina', 'BCRA'),
    ('Central Bank of Armenia', 'CBA'),
    ('Central Bank of Aruba', 'CBA'),
    ('Central Bank of Azerbaijan', 'CBA'),
    ('Central Bank of Bahrain', 'CBB'),
    ('Central Bank of Barbados', 'CBB'),
    ('Central Bank of Belize', 'CBB'),
    ('Central Bank of Bolivia', 'BCB'),
    ('Central Bank of Bosnia and Herzegovina', 'CBBH'),
    ('Central Bank of Brazil', 'BCB'),
    ('Central Bank of Chile', 'BCC'),
    ('Central Bank of Comoros', 'BCC'),
    ('Central Bank of Congo', 'BCC'),
    ('Central Bank of Costa Rica', 'BCCR'),
    ('Central Bank of Cuba', 'BCC'),
    ('Central Bank of Curacao and Sint Maarten', 'CBCS'),
    ('Central Bank of Cyprus', 'CBC'),
    ('Central Bank of Djibouti', 'BCD'),
    ('Central Bank of Ecuador', 'BCE'),
    ('Central Bank of Egypt', 'CBE'),
    ('Central Bank of Eswatini', 'CBS'),
    ('Central Bank of Honduras', 'BCH'),
    ('Central Bank of Iceland', 'CBI'),
    ('Central Bank of Iran', 'CBI'),
    ('Central Bank of Iraq', 'CBI'),
    ('Central Bank of Ireland', 'CBI'),
    ('Central Bank of Jordan', 'CBJ'),
    ('Central Bank of Kenya', 'CBK'),
    ('Central Bank of Kuwait', 'CBK'),
    ('Central Bank of Lesotho', 'CBL'),
    ('Central Bank of Liberia', 'CBL'),
    ('Central Bank of Libya', 'CBL'),
    ('Central Bank of Luxembourg', 'BCL'),
    ('Central Bank of Madagascar', 'BCM'),
    ('Central Bank of Malaysia', 'BNM'),
    ('Central Bank of Malta', 'CBM'),
    ('Central Bank of Mauritania', 'BCM'),
    ('Central Bank of Montenegro', 'CBCG'),
    ('Central Bank of Myanmar', 'CBM'),
    ('Central Bank of Nicaragua', 'BCN'),
    ('Central Bank of Nigeria', 'CBN'),
    ('Central Bank of Oman', 'CBO'),
    ('Central Bank of Paraguay', 'BCP'),
    ('Central Bank of Russia', 'CBR'),
    ('Central Bank of Samoa', 'CBS'),
    ('Central Bank of Sao Tome and Principe', 'BCSTP'),
    ('Central Bank of Seychelles', 'CBS'),
    ('Central Bank of Solomon Islands', 'CBSI'),
    ('Central Bank of Somalia', 'CBS'),
    ('Central Bank of Sri Lanka', 'CBSL'),
    ('Central Bank of Sudan', 'CBOS'),
    ('Central Bank of Suriname', 'CBvS'),
    ('Central Bank of Syria', 'CBS'),
    ('Central Bank of The Bahamas', 'CBOB'),
    ('Central Bank of the Democratic People''s Republic of Korea', 'CB'),
    ('Central Bank of the Dominican Republic', 'BCRD'),
    ('Central Bank of The Gambia', 'CBG'),
    ('Central Bank of the Republic of China', 'CBC'),
    ('Central Bank of the Republic of Guinea', 'BCRG'),
    ('Central Bank of the Republic of Kosovo', 'CBK'),
    ('Central Bank of the Republic of San Marino', 'CBSM'),
    ('Central Bank of the Republic of Turkey', 'CBRT'),
    ('Central Bank of the UAE', 'CBUAE'),
    ('Central Bank of Timor-Leste', 'BCTL'),
    ('Central Bank of Trinidad and Tobago', 'CBTT'),
    ('Central Bank of Tunisia', 'BCT'),
    ('Central Bank of Turkmenistan', 'CBRT'),
    ('Central Bank of Uruguay', 'BCU'),
    ('Central Bank of Uzbekistan', 'CB'),
    ('Central Bank of Venezuela', 'BCV'),
    ('Central Bank of West African States', 'BCEAO'),
    ('Central Bank of Yemen', 'CBY'),
    ('Central Reserve Bank of El Salvador', 'BCRES'),
    ('Central Reserve Bank of Peru', 'BCRP'),
    ('Croatian National Bank', 'HNB'),
    ('Czech National Bank', 'CNB'),
    ('Da Afghanistan Bank', 'DAB'),
    ('Danmarks Nationalbank', 'DN'),
    ('De Nederlandsche Bank', 'DNB'),
    ('Deutsche Bundesbank', 'Bundesbank'),
    ('Eastern Caribbean Central Bank', 'ECCB'),
    ('Eesti Pank', 'EKP'),
    ('European Central Bank', 'ECB'),
    ('Federal Reserve Bank of NY', 'FRBNY'),
    ('Federal Reserve System', 'FRB'),
    ('Government of Gibraltar'),
    ('Hong Kong Monetary Authority', 'HKMA'),
    ('Isle of Man Government'),
    ('Jersey Financial Services Commission', 'JFSC'),
    ('Latvijas Banka', 'LB'),
    ('Liechtensteinische Landesbank', 'LLB'),
    ('Magyar Nemzeti Bank', 'MNB'),
    ('Maldives Monetary Authority', 'MMA'),
    ('Monetary Authority of Macao', 'AMCM'),
    ('Monetary Authority of Singapore', 'MAS'),
    ('National Bank of Angola', 'BNA'),
    ('National Bank of Belgium', 'NBB'),
    ('National Bank of Cambodia', 'NBC'),
    ('National Bank of Ethiopia', 'NBE'),
    ('National Bank of Georgia', 'NBG'),
    ('National Bank of Kazakhstan', 'NBK'),
    ('National Bank of Moldova', 'NBM'),
    ('National Bank of Panama', 'BNP'),
    ('National Bank of Poland', 'NBP'),
    ('National Bank of Romania', 'BNR'),
    ('National Bank of Rwanda', 'BNR'),
    ('National Bank of Serbia', 'NBS'),
    ('National Bank of Slovakia', 'NBS'),
    ('National Bank of Tajikistan', 'NBT'),
    ('National Bank of the Kyrgyz Republic', 'NBKR'),
    ('National Bank of the Republic of Belarus', 'NBRB'),
    ('National Bank of the Republic of North Macedonia', 'NBRM'),
    ('National Bank of Ukraine', 'NBU'),
    ('National Reserve Bank of Tonga', 'NRBT'),
    ('Nepal Rastra Bank', 'NRB'),
    ('Norges Bank', 'NB'),
    ('Palestine Monetary Authority', 'PMA'),
    ('People''s Bank of China', 'PBOC'),
    ('Qatar Central Bank', 'QCB'),
    ('Reserve Bank of Australia', 'RBA'),
    ('Reserve Bank of Fiji', 'RBF'),
    ('Reserve Bank of India', 'RBI'),
    ('Reserve Bank of Malawi', 'RBM'),
    ('Reserve Bank of New Zealand', 'RBNZ'),
    ('Reserve Bank of Vanuatu', 'RBV'),
    ('Reserve Bank of Zimbabwe', 'RBZ'),
    ('Royal Monetary Authority of Bhutan', 'RMA'),
    ('Saudi Arabian Monetary Authority', 'SAMA'),
    ('South African Reserve Bank', 'SARB'),
    ('State Bank of Pakistan', 'SBP'),
    ('State Bank of Vietnam', 'SBV'),
    ('Sveriges Riksbank', 'Sveriges Riksbank'),
    ('Swiss National Bank', 'SNB'),
    ('Vatican Bank', 'VB');

