/*
 ***********************************************************************************************************
 * @file
 * l_currency_unit.sql
 *
 * Lookup table - currency unit lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_currency_unit;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_currency_unit
(
    code TEXT NOT NULL
        CHECK (code ~ '^[A-Z]{3}$'),
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_text(name, FALSE) IS NULL),

    PRIMARY KEY (code),
    UNIQUE (name)
);

COMMENT ON TABLE ce_warehouse.l_currency_unit
    IS 'Lookup table - currency unit lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_currency_unit (code, name)
VALUES
    ('AED', 'Dirham'),
    ('AFN', 'Afghani'),
    ('ALL', 'Lek'),
    ('AMD', 'Dram'),
    ('ANG', 'Guilder'),
    ('AOA', 'Kwanza'),
    ('ARS', 'Peso'),
    ('AUD', 'Dollar'),
    ('AWG', 'Florin'),
    ('AZN', 'Manat'),
    ('BAM', 'Convertible Mark'),
    ('BBD', 'Dollar'),
    ('BDT', 'Taka'),
    ('BGN', 'Lev'),
    ('BHD', 'Dinar'),
    ('BIF', 'Franc'),
    ('BMD', 'Dollar'),
    ('BND', 'Dollar'),
    ('BOB', 'Boliviano'),
    ('BRL', 'Real'),
    ('BSD', 'Dollar'),
    ('BTN', 'Ngultrum'),
    ('BWP', 'Pula'),
    ('BYN', 'Ruble'),
    ('BZD', 'Dollar'),
    ('CAD', 'Dollar'),
    ('CDF', 'Franc'),
    ('CHF', 'Swiss Franc'),
    ('CLP', 'Peso'),
    ('CNY', 'Yuan'),
    ('COP', 'Peso'),
    ('CRC', 'Colon'),
    ('CUP', 'Peso'),
    ('CVE', 'Escudo'),
    ('CZK', 'Koruna'),
    ('DJF', 'Franc'),
    ('DKK', 'Krone'),
    ('DOP', 'Peso'),
    ('DZD', 'Dinar'),
    ('EGP', 'Pound'),
    ('ERN', 'Nakfa'),
    ('ETB', 'Birr'),
    ('EUR', 'Euro'),
    ('FJD', 'Dollar'),
    ('FKP', 'Pound'),
    ('GBP', 'Pound'),
    ('GEL', 'Lari'),
    ('GHS', 'Cedi'),
    ('GIP', 'Pound'),
    ('GMD', 'Dalasi'),
    ('GNF', 'Franc'),
    ('GTQ', 'Quetzal'),
    ('GYD', 'Dollar'),
    ('HKD', 'Dollar'),
    ('HNL', 'Lempira'),
    ('HRK', 'Kuna'),
    ('HTG', 'Gourde'),
    ('HUF', 'Forint'),
    ('IDR', 'Rupiah'),
    ('ILS', 'Shekel'),
    ('INR', 'Rupee'),
    ('IQD', 'Dinar'),
    ('IRR', 'Rial'),
    ('ISK', 'Krona'),
    ('JMD', 'Dollar'),
    ('JOD', 'Dinar'),
    ('JPY', 'Yen'),
    ('KES', 'Shilling'),
    ('KGS', 'Som'),
    ('KHR', 'Riel'),
    ('KMF', 'Franc'),
    ('KPW', 'Won'),
    ('KRW', 'Won'),
    ('KWD', 'Dinar'),
    ('KYD', 'Dollar'),
    ('KZT', 'Tenge'),
    ('LAK', 'Kip'),
    ('LBP', 'Pound'),
    ('LKR', 'Rupee'),
    ('LRD', 'Dollar'),
    ('LSL', 'Loti'),
    ('LYD', 'Dinar'),
    ('MAD', 'Dirham'),
    ('MDL', 'Leu'),
    ('MGA', 'Ariary'),
    ('MKD', 'Denar'),
    ('MMK', 'Kyat'),
    ('MNT', 'Tugrik'),
    ('MOP', 'Pataca'),
    ('MRU', 'Ouguiya'),
    ('MUR', 'Rupee'),
    ('MVR', 'Rufiyaa'),
    ('MWK', 'Kwacha'),
    ('MXN', 'Peso'),
    ('MYR', 'Ringgit'),
    ('MZN', 'Metical'),
    ('NAD', 'Dollar'),
    ('NGN', 'Naira'),
    ('NIO', 'Cordoba'),
    ('NOK', 'Krone'),
    ('NPR', 'Rupee'),
    ('NZD', 'Dollar'),
    ('OMR', 'Rial'),
    ('PAB', 'Balboa'),
    ('PEN', 'Sol'),
    ('PGK', 'Kina'),
    ('PHP', 'Peso'),
    ('PKR', 'Rupee'),
    ('PLN', 'Zloty'),
    ('PYG', 'Guarani'),
    ('QAR', 'Riyal'),
    ('RON', 'Leu'),
    ('RSD', 'Dinar'),
    ('RUB', 'Ruble'),
    ('RWF', 'Franc'),
    ('SAR', 'Riyal'),
    ('SBD', 'Dollar'),
    ('SCR', 'Rupee'),
    ('SDG', 'Pound'),
    ('SEK', 'Krona'),
    ('SGD', 'Dollar'),
    ('SHP', 'Pound'),
    ('SLL', 'Leone'),
    ('SOS', 'Shilling'),
    ('SRD', 'Dollar'),
    ('SSP', 'Pound'),
    ('STN', 'Dobra'),
    ('SYP', 'Pound'),
    ('SZL', 'Lilangeni'),
    ('THB', 'Baht'),
    ('TJS', 'Somoni'),
    ('TMT', 'Manat'),
    ('TND', 'Dollar'),
    ('TOP', 'Pa''anga'),
    ('TRY', 'Lira'),
    ('TTD', 'Dollar'),
    ('TWD', 'Dollar'),
    ('TZS', 'Shilling'),
    ('UAH', 'Hryvnia'),
    ('UGX', 'Shilling'),
    ('USD', 'Dollar'),
    ('UYU', 'Peso'),
    ('UZS', 'Som'),
    ('VES', 'Bolivar'),
    ('VND', 'Dong'),
    ('VUV', 'Vatu'),
    ('WST', 'Tala'),
    ('XAF', 'CFA Franc BEAC'),
    ('XCD', 'East Caribbean Dollar'),
    ('XOF', 'CFA Franc BCEAO'),
    ('XPF', 'CFP Franc'),
    ('YER', 'Rial'),
    ('ZAR', 'Rand'),
    ('ZMW', 'Kwacha'),
    ('ZWL', 'Dollar');
