/*
 ***********************************************************************************************************
 * @file
 * l_data_transformation.sql
 *
 * Lookup table - data transFORMATion lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_data_transformation;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_data_transformation
(
    pk_data_transformation SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    code TEXT NOT NULL
        CHECK (code ~ '[A-Z0-9%]{1,10}'),

    PRIMARY KEY (pk_data_transformation),
    UNIQUE (code)
);

COMMENT ON TABLE ce_warehouse.l_data_transformation
    IS 'Lookup table - data transformation lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_data_transformation (code)
VALUES
    ('%'),
    ('%GDP'),
    ('3M3M'),
    ('3M3MA'),
    ('3MA'),
    ('3MYY'),
    ('6MA'),
    ('ABSCH'),
    ('DIX'),
    ('IX'),
    ('LEVEL'),
    ('LVL'),
    ('MM'),
    ('MMA'),
    ('PPTS'),
    ('QA'),
    ('QQ'),
    ('RATIO'),
    ('SDEV'),
    ('YY'),
    ('Z');
