/*
 ***********************************************************************************************************
 * @file
 * l_geo_category.sql
 *
 * Lookup table - GEO category lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_geo_category;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_geo_category
(
    pk_geo_category SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(name) IS NULL),

    PRIMARY KEY (pk_geo_category),
    UNIQUE (name)
);

COMMENT ON TABLE ce_warehouse.l_geo_category
    IS 'Lookup table - GEO category lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_geo_category (name)
VALUES
    ('Country'),
    ('Region'),
    ('Subnational'),
    ('Unknown');
