/*
 ***********************************************************************************************************
 * @file
 * l_ind_broad_category.sql
 *
 * Lookup table - IND broad category lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_ind_broad_category;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_ind_broad_category
(
    pk_ind_broad_category SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_name(name) IS NULL),

    PRIMARY KEY (pk_ind_broad_category),
    UNIQUE (name)
);

COMMENT ON TABLE ce_warehouse.l_ind_broad_category
    IS 'Lookup table - IND broad category lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_ind_broad_category (name)
VALUES
    ('Climate'),
    ('Commodities'),
    ('Macro'),
    ('Prroperty');