/*
 ***********************************************************************************************************
 * @file
 * l_ind_category_broad.sql
 *
 * Lookup table - IND broad category lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_ind_category_broad;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_ind_category_broad
(
    pk_ind_category_broad SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val__is_name(name) IS NULL),

    PRIMARY KEY (pk_ind_category_broad),
    UNIQUE (name)
);

COMMENT ON TABLE ce_warehouse.l_ind_category_broad
    IS 'Lookup table - IND broad category lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_ind_category_broad (name)
VALUES
    ('Climate'),
    ('Commodities'),
    ('Macro'),
    ('Prroperty');