/*
 ***********************************************************************************************************
 * @file
 * l_political_alignment.sql
 *
 * Lookup table - political alignment lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_political_alignment;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_political_alignment
(
    pk_political_alignment SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val__is_name(name) IS NULL),

    PRIMARY KEY (pk_political_alignment),
    UNIQUE (name)
);

COMMENT ON TABLE ce_warehouse.l_political_alignment
    IS 'Lookup table - political alignment lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_political_alignment (name)
VALUES
    ('Strong US'),
    ('Leans US'),
    ('Unaligned'),
    ('Leans China'),
    ('Strong China');