/*
 ***********************************************************************************************************
 * @file
 * l_politcal_alignment.sql
 *
 * Lookup table - political alignment lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_political_alignment;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_political_alignment
(
    pk_pa INT GENERATED BY DEFAULT AS IDENTITY,
    code TEXT NOT NULL
        CHECK (code ~ '^[A-Z][A-Za-z0-9 ]*$'),
    PRIMARY KEY (pk_pa),
    UNIQUE (code)
);

COMMENT ON TABLE ce_warehouse.l_political_alignment
    IS 'Lookup table - political alignment lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_political_alignment (code)
VALUES
    ('Strong US'),
    ('Leans US'),
    ('Unaligned'),
    ('Leans China'),
    ('Strong China');