/*
 ***********************************************************************************************************
 * @file
 * l_stock_market.sql
 *
 * Lookup table - central bank lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_stock_market;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_stock_market
(
    code TEXT NOT NULL
        CHECK (code ~ '^[A-Z].*$' ce_warehouse.fx_val_is_text(name)),
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_text(name)),

    PRIMARY KEY (code),
    UNIQUE (name)
);

COMMENT ON TABLE ce_warehouse.l_stock_market
    IS 'Lookup table - stock market lookup';

/**
 * Pre-populate with known values. Update as required.
 */
INSERT INTO ce_warehouse.l_stock_market (code, name)
VALUES
    ('ADX', 'Abu Dhabi Securities Exchange'),
    ('AFSE', 'Afghanistan Stock Exchange'),
    ('ASE', 'Athens Stock Exchange'),
    ('ASE', 'Amman Stock Exchange'),
    ('BAX', 'Bourse d''Alger'),
    ('BBV', 'Bolivian Stock Exchange'),
    ('BCS', 'Santiago Stock Exchange'),
    ('BCSE', 'Belarusian Currency and Stock Exchange'),
    ('BCV', 'Bolsa Centroamericana de Valores'),
    ('BDCA', 'Andorra Stock Exchange'),
    ('BELEX', 'Belgrade Stock Exchange'),
    ('BHB', 'Bahrain Bourse'),
    ('BISX', 'Bahamas International Securities Exchange'),
    ('BK', 'Boursa Kuwait'),
    ('BME', 'Bolsa de Madrid'),
    ('BNCR', 'Bolsa Nacional de Valores'),
    ('BODIVA', 'Bolsa de Divida e Valores de Angola'),
    ('Bolsa', 'Mexican Stock Exchange'),
    ('Bovespa', 'B3 (Brasil Bolsa Balcao)'),
    ('BRVM', 'Regional Stock Exchange of West Africa'),
    ('BSE', 'Budapest Stock Exchange'),
    ('BSE', 'Beirut Stock Exchange'),
    ('BSE', 'Botswana Stock Exchange'),
    ('BSE', 'Baku Stock Exchange'),
    ('BSE', 'Bulgarian Stock Exchange'),
    ('BSE', 'Barbados Stock Exchange'),
    ('BSSE', 'Bratislava Stock Exchange'),
    ('B&V', 'Bolsa de Valores Nacional'),
    ('BVB', 'Bucharest Stock Exchange'),
    ('BVC', 'Cape Verde Stock Exchange'),
    ('BVC', 'Colombia Stock Exchange'),
    ('BVC', 'Casablanca Stock Exchange'),
    ('BVDN', 'Bolsa de Valores de Nicaragua'),
    ('BVES', 'Bolsa de Valores de El Salvador'),
    ('BVL', 'Lima Stock Exchange'),
    ('BVMB', 'Bolsa de Valores de Montevideo'),
    ('BVMT', 'Bourse de Tunis'),
    ('BVPASA', 'Bolsa de Valores y Productos de Asuncion'),
    ('BVPSA', 'Bolsa de Valores de Panama'),
    ('BVRD', 'Bolsa de Valores de la Republica Dominicana'),
    ('BYMA', 'Buenos Aires Stock Exchange'),
    ('CSE', 'Caracas Stock Exchange'),
    ('CSE', 'Colombo Stock Exchange'),
    ('CSE', 'Cyprus Stock Exchange'),
    ('CSI 300', 'Shanghai Stock Exchange'),
    ('CSX', 'Cayman Islands Stock Exchange'),
    ('CSX', 'Cambodia Securities Exchange'),
    ('DAX 30', 'Frankfurt Stock Exchange'),
    ('DSE', 'Dar es Salaam Stock Exchange'),
    ('DSE', 'Dhaka Stock Exchange'),
    ('DSX', 'Douala Stock Exchange'),
    ('ECSE', 'Eastern Caribbean Securities Exchange'),
    ('ECX', 'Ethiopia Commodity Exchange'),
    ('EGX 30', 'Egyptian Exchange'),
    ('Euronext', 'Euronext Dublin'),
    ('Euronext', 'CAC 40'),
    ('Euronext', 'Euronext Amsterdam'),
    ('Euronext', 'Euronext Lisbon'),
    ('Euronext', 'Euronext Brussels'),
    ('FTSE 100', 'London Stock Exchange'),
    ('FTSE MIB', 'Borsa Italiana'),
    ('GASCI', 'Guyana Association of Securities Companies and Intermediaries (GASCI)'),
    ('GPW', 'Warsaw Stock Exchange'),
    ('GSE', 'Ghana Stock Exchange'),
    ('GSE', 'Georgian Stock Exchange'),
    ('HKEX', 'Hong Kong Stock Exchange'),
    ('HOSE', 'Ho Chi Minh Stock Exchange'),
    ('HSE', 'Haitian Stock Exchange'),
    ('IDX', 'Indonesia Stock Exchange'),
    ('ISE 100', 'Borsa Istanbul'),
    ('ISX', 'Iraq Stock Exchange'),
    ('JALSH', 'Johannesburg Stock Exchange'),
    ('JSE', 'Jamaica Stock Exchange'),
    ('KASE', 'Kazakhstan Stock Exchange'),
    ('KRX', 'Korea Exchange'),
    ('KSE', 'Kyrgyz Stock Exchange'),
    ('LJSE', 'Ljubljana Stock Exchange'),
    ('LSE', 'Lao Securities Exchange'),
    ('LuSE', 'Lusaka Securities Exchange'),
    ('LuxSE', 'Luxembourg Stock Exchange'),
    ('MNSE', 'Montenegro Stock Exchange'),
    ('MOEX', 'Moscow Exchange'),
    ('MSCI EM ($ basis)', NULL),
    ('MSE', 'Malta Stock Exchange'),
    ('MSE', 'Macedonian Stock Exchange'),
    ('MSE', 'Moldova Stock Exchange'),
    ('MSE', 'Malawi Stock Exchange'),
    ('MSE', 'Mongolian Stock Exchange'),
    ('MSM', 'Muscat Securities Market'),
    ('MYX', 'Bursa Malaysia'),
    ('NASDAQ', 'NASDAQ Helsinki'),
    ('NASDAQ', 'NASDAQ OMX Armenia'),
    ('NASDAQ', 'NASDAQ Iceland'),
    ('NASDAQ', 'NASDAQ Stockholm'),
    ('NASDAQ', 'NASDAQ Copenhagen'),
    ('NGSE', 'Nigerian Stock Exchange'),
    ('NSE', 'Nairobi Securities Exchange'),
    ('NSE', 'Nasdaq Riga'),
    ('NSE', 'Nasdaq Vilnius'),
    ('NSX', 'Namibian Stock Exchange'),
    ('NZX', 'New Zealand Stock Exchange'),
    ('OSE', 'Oslo Stock Exchange'),
    ('PEX', 'Palestine Exchange'),
    ('POMSoX', 'Port Moresby Stock Exchange'),
    ('PSE', 'Prague Stock Exchange'),
    ('PSE', 'Philippine Stock Exchange'),
    ('PSX', 'Pakistan Stock Exchange'),
    ('QSE', 'Qatar Stock Exchange'),
    ('QSE', 'Quito Stock Exchange'),
    ('RSE', 'Rwanda Stock Exchange'),
    ('SASE', 'Sarajevo Stock Exchange'),
    ('SEM', 'Stock Exchange of Mauritius'),
    ('Sensex', 'Bombay Stock Exchange'),
    ('SET', 'Stock Exchange of Thailand'),
    ('SGX', 'Singapore Exchange'),
    ('SIX', 'SIX Swiss Exchange'),
    ('S&P 500', 'New York Stock Exchange'),
    ('S&P/ASX 200', 'Australian Securities Exchange'),
    ('S&P/TSX', 'Toronto Stock Exchange'),
    ('SPX', 'South Pacific Stock Exchange'),
    ('TALSE', 'Nasdaq Tallinn'),
    ('TASE', 'Tel Aviv Stock Exchange'),
    ('TASI', 'Tadawul'),
    ('TOPIX', 'Tokyo Stock Exchange'),
    ('TSE', 'Tehran Stock Exchange'),
    ('TSE', 'Tirana Stock Exchange'),
    ('TSX', 'Tajikistan Stock Exchange'),
    ('TTSE', 'Trinidad and Tobago Stock Exchange'),
    ('TWSE', 'Taiwan Stock Exchange'),
    ('USE', 'Uganda Securities Exchange'),
    ('UX', 'Ukrainian Exchange'),
    ('UZSE', 'Republican Stock Exchange of Uzbekistan'),
    ('VCSE', 'Vatican City Stock Exchange'),
    ('WBAG', 'Vienna Stock Exchange'),
    ('YSX', 'Yangon Stock Exchange'),
    ('ZSE', 'Zagreb Stock Exchange'),
    ('ZSE', 'Zimbabwe Stock Excahnge');
