/*
 ***********************************************************************************************************
 * @file
 * l_stock_market.sql
 *
 * Lookup table - central bank lookup.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.l_stock_market;

CREATE TABLE IF NOT EXISTS ce_warehouse.l_stock_market
(
    name TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_text(name, FALSE) IS NULL),
    short_code TEXT NOT NULL
        CHECK (short_code ~ '^[A-Z]' AND ce_warehouse.fx_val_is_text(short_code) IS NULL),

    PRIMARY KEY (name)
);

COMMENT ON TABLE ce_warehouse.l_stock_market
    IS 'Lookup table - stock market lookup';

/**
 * Pre-populate with known values. Update as required.
 *
 * @todo - discuss fix for Athens Stock Exchange code from ASE to ATHEX
        also codes arent unique, WTF??
 */
INSERT INTO ce_warehouse.l_stock_market (name, short_code)
VALUES
    ('Abu Dhabi Securities Exchange', 'ADX'),
    ('Afghanistan Stock Exchange', 'AFSE'),
    ('Amman Stock Exchange', 'ASE'),
    ('Athens Stock Exchange', 'ATHEX'),
    ('Bourse d''Alger', 'BAX'),
    ('Bolivian Stock Exchange', 'BBV'),
    ('Santiago Stock Exchange', 'BCS'),
    ('Belarusian Currency and Stock Exchange', 'BCSE'),
    ('Bolsa Centroamericana de Valores', 'BCV'),
    ('Andorra Stock Exchange', 'BDCA'),
    ('Belgrade Stock Exchange', 'BELEX'),
    ('Bahrain Bourse', 'BHB'),
    ('Bahamas International Securities Exchange', 'BISX'),
    ('Boursa Kuwait', 'BK'),
    ('Bolsa de Madrid', 'BME'),
    ('Bolsa Nacional de Valores', 'BNCR'),
    ('Bolsa de Divida e Valores de Angola', 'BODIVA'),
    ('Mexican Stock Exchange', 'Bolsa'),
    ('B3 (Brasil Bolsa Balcao)', 'Bovespa'),
    ('Regional Stock Exchange of West Africa', 'BRVM'),
    ('Budapest Stock Exchange', 'BSE'),
    ('Beirut Stock Exchange', 'BSE'),
    ('Botswana Stock Exchange', 'BSE'),
    ('Baku Stock Exchange', 'BSE'),
    ('Bulgarian Stock Exchange', 'BSE'),
    ('Barbados Stock Exchange', 'BSE'),
    ('Bratislava Stock Exchange', 'BSSE'),
    ('Bolsa de Valores Nacional', 'B&V'),
    ('Bucharest Stock Exchange', 'BVB'),
    ('Cape Verde Stock Exchange', 'BVC'),
    ('Colombia Stock Exchange', 'BVC'),
    ('Casablanca Stock Exchange', 'BVC'),
    ('Bolsa de Valores de Nicaragua', 'BVDN'),
    ('Bolsa de Valores de El Salvador', 'BVES'),
    ('Lima Stock Exchange', 'BVL'),
    ('Bolsa de Valores de Montevideo', 'BVMB'),
    ('Bourse de Tunis', 'BVMT'),
    ('Bolsa de Valores y Productos de Asuncion', 'BVPASA'),
    ('Bolsa de Valores de Panama', 'BVPSA'),
    ('Bolsa de Valores de la Republica Dominicana', 'BVRD'),
    ('Buenos Aires Stock Exchange', 'BYMA'),
    ('Caracas Stock Exchange', 'CSE'),
    ('Colombo Stock Exchange', 'CSE'),
    ('Cyprus Stock Exchange', 'CSE'),
    ('Shanghai Stock Exchange', 'CSI 300'),
    ('Cayman Islands Stock Exchange', 'CSX'),
    ('Cambodia Securities Exchange', 'CSX'),
    ('Frankfurt Stock Exchange', 'DAX 30'),
    ('Dar es Salaam Stock Exchange', 'DSE'),
    ('Dhaka Stock Exchange', 'DSE'),
    ('Douala Stock Exchange', 'DSX'),
    ('Eastern Caribbean Securities Exchange', 'ECSE'),
    ('Ethiopia Commodity Exchange', 'ECX'),
    ('Egyptian Exchange', 'EGX 30'),
    ('Euronext Dublin', 'Euronext'),
    ('CAC 40', 'Euronext'),
    ('Euronext Amsterdam', 'Euronext'),
    ('Euronext Lisbon', 'Euronext'),
    ('Euronext Brussels', 'Euronext'),
    ('London Stock Exchange', 'FTSE 100'),
    ('Borsa Italiana', 'FTSE MIB'),
    ('Guyana Association of Securities Companies and Intermediaries (GASCI)', 'GASCI'),
    ('Warsaw Stock Exchange', 'GPW'),
    ('Ghana Stock Exchange', 'GSE'),
    ('Georgian Stock Exchange', 'GSE'),
    ('Hong Kong Stock Exchange', 'HKEX'),
    ('Ho Chi Minh Stock Exchange', 'HOSE'),
    ('Haitian Stock Exchange', 'HSE'),
    ('Indonesia Stock Exchange', 'IDX'),
    ('Borsa Istanbul', 'ISE 100'),
    ('Iraq Stock Exchange', 'ISX'),
    ('Johannesburg Stock Exchange', 'JALSH'),
    ('Jamaica Stock Exchange', 'JSE'),
    ('Kazakhstan Stock Exchange', 'KASE'),
    ('Korea Exchange', 'KRX'),
    ('Kyrgyz Stock Exchange', 'KSE'),
    ('Ljubljana Stock Exchange', 'LJSE'),
    ('Lao Securities Exchange', 'LSE'),
    ('Lusaka Securities Exchange', 'LuSE'),
    ('Luxembourg Stock Exchange', 'LuxSE'),
    ('Montenegro Stock Exchange', 'MNSE'),
    ('Moscow Exchange', 'MOEX'),
    ('MSCI EM ($ basis)', 'MSCI EM ($ basis)'),
    ('Malta Stock Exchange', 'MSE'),
    ('Macedonian Stock Exchange', 'MSE'),
    ('Moldova Stock Exchange', 'MSE'),
    ('Malawi Stock Exchange', 'MSE'),
    ('Mongolian Stock Exchange', 'MSE'),
    ('Muscat Securities Market', 'MSM'),
    ('Bursa Malaysia', 'MYX'),
    ('NASDAQ Helsinki', 'NASDAQ'),
    ('NASDAQ OMX Armenia', 'NASDAQ'),
    ('NASDAQ Iceland', 'NASDAQ'),
    ('NASDAQ Stockholm', 'NASDAQ'),
    ('NASDAQ Copenhagen', 'NASDAQ'),
    ('Nigerian Stock Exchange', 'NGSE'),
    ('Nairobi Securities Exchange', 'NSE'),
    ('Nasdaq Riga', 'NSE'),
    ('Nasdaq Vilnius', 'NSE'),
    ('Namibian Stock Exchange', 'NSX'),
    ('New Zealand Stock Exchange', 'NZX'),
    ('Oslo Stock Exchange', 'OSE'),
    ('Palestine Exchange', 'PEX'),
    ('Port Moresby Stock Exchange', 'POMSoX'),
    ('Prague Stock Exchange', 'PSE'),
    ('Philippine Stock Exchange', 'PSE'),
    ('Pakistan Stock Exchange', 'PSX'),
    ('Qatar Stock Exchange', 'QSE'),
    ('Quito Stock Exchange', 'QSE'),
    ('Rwanda Stock Exchange', 'RSE'),
    ('Sarajevo Stock Exchange', 'SASE'),
    ('Stock Exchange of Mauritius', 'SEM'),
    ('Bombay Stock Exchange', 'Sensex'),
    ('Stock Exchange of Thailand', 'SET'),
    ('Singapore Exchange', 'SGX'),
    ('SIX Swiss Exchange', 'SIX'),
    ('New York Stock Exchange', 'S&P 500'),
    ('Australian Securities Exchange', 'S&P/ASX 200'),
    ('Toronto Stock Exchange', 'S&P/TSX'),
    ('South Pacific Stock Exchange', 'SPX'),
    ('Nasdaq Tallinn', 'TALSE'),
    ('Tel Aviv Stock Exchange', 'TASE'),
    ('Tadawul', 'TASI'),
    ('Tokyo Stock Exchange', 'TOPIX'),
    ('Tehran Stock Exchange', 'TSE'),
    ('Tirana Stock Exchange', 'TSE'),
    ('Tajikistan Stock Exchange', 'TSX'),
    ('Trinidad and Tobago Stock Exchange', 'TTSE'),
    ('Taiwan Stock Exchange', 'TWSE'),
    ('Uganda Securities Exchange', 'USE'),
    ('Ukrainian Exchange', 'UX'),
    ('Republican Stock Exchange of Uzbekistan', 'UZSE'),
    ('Vatican City Stock Exchange', 'VCSE'),
    ('Vienna Stock Exchange', 'WBAG'),
    ('Yangon Stock Exchange', 'YSX'),
    ('Zagreb Stock Exchange', 'ZSE'),
    ('Zimbabwe Stock Excahnge', 'ZSE');
