/*
 ***********************************************************************************************************
 * @file
 * s__trigger_status.sql
 *
 * System table - lets batch work temporarily disable named triggers, e.g. to allow for bulk loading of data.
 *
 * NOTE, we don't use the text validation functions in any of the "s_" system tables because they are
 * potentially used by the validation functions, so we need to have more basic validation rules in place
 * to avoid circular references.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.s__trigger_status;

CREATE TABLE IF NOT EXISTS ce_warehouse.s__trigger_status
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    name TEXT NOT NULL
        CHECK (name ~ '^tg__[a-z0-9_]+[a-z0-9]$'),  -- Trigger name format
    status TEXT NOT NULL
        CHECK (status IN ('enabled', 'disabled')),  -- Trigger status

    PRIMARY KEY (idx),
    UNIQUE (name)
);

COMMENT ON TABLE ce_warehouse.s__trigger_status
    IS 'System table - lets batch work temporarily disable named triggers, e.g. to allow for bulk loading of data';
