/*
 ***********************************************************************************************************
 * @file
 * s_text_rules.sql
 *
 * System table - text field validation rules, see fx_val_is_text & fx_val_is_name.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.s_text_rules;

CREATE TABLE IF NOT EXISTS ce_warehouse.s_text_rules
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    text_or_name TEXT NOT NULL
        CHECK (text_or_name IN ('N', 'T')),
    column_name TEXT NOT NULL
        CHECK (column_name = 'DEFAULT' OR column_name ~ '^[a-z0-9][a-z0-9*_.][a-z0-9*]$'),
    description TEXT NOT NULL,

    allow_consecutive_ws BOOL NOT NULL DEFAULT FALSE,
    allow_leading_or_trailing_ws BOOL NOT NULL DEFAULT FALSE,
    allow_unbalanced_parentheses BOOL NOT NULL DEFAULT FALSE,

    single_char_regex TEXT
        CHECK (
            (min_length > 1 AND single_char_regex IS NULL)
            OR (min_length = 1 AND single_char_regex IS NOT NULL)
    ),

    full_regex TEXT NOT NULL,

    -- NULL rules at the table level will override these
    min_length INT NOT NULL DEFAULT 1
        CHECK (min_length >= 1),
    max_length INT NOT NULL DEFAULT 255
        CHECK (max_length >= min_length),

    PRIMARY KEY (idx),
    UNIQUE (text_or_name, column_name)
);

COMMENT ON TABLE ce_warehouse.s_text_rules
    IS 'System table - text field validation rules, see fx_val_is_text & fx_val_is_name';

/**
 * Pre-populate with known values.
 *
 * NOTE:
 *
 * - "DEFAULT" column_name is used by the validation functions when no specific rule is found for a column.
 * - Allowed text expessions are: ANY (no validation), ASCII, PRINTABLE, or regex expression (undelimited).
 *
 * Care should be taken to ensure regex expressions are valid and performant. Changes may have unexpected consequences
 * like causing all control tables  to be marked as invalid, so always test your regexes first.
 */
INSERT INTO ce_warehouse.s_text_rules (
    text_or_name, column_name, description, allow_consecutive_ws, allow_leading_or_trailing_ws, allow_unbalanced_parenthesis, single_char_regex, full_regex
)
VALUES
    (
     'N',
     'DEFAULT',
     'Default is-name rule',
     FALSE,
     FALSE,
        FALSE,
     '^[A-Z0-9%£$€]$',
     '^[A-Z0-9<>''"(%£$€][A-Za-z0-9 &/:,;.<>=''"()%£$€+-]*[A-Za-z0-9).%£$€+"]$'
    ),
    (
     'T',
     'DEFAULT',
     'Default is-text rule',
     TRUE,
     FALSE,
     TRUE,
     'ANY',
     'ANY'
    );
