/*
 ***********************************************************************************************************
 * @file
 * s_text_rules.sql
 *
 * System table - text field validation rules, see fx_val_is_text, fx_val_is_code & fx_val_is_name.
  *
 * NOTE, we don't use the text validation functions in any of the "s_" system tables because they are
 * potentially used by the validation functions, so we need to have more basic validation rules in place
 * to avoid circular references.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.s_text_rules;

CREATE TABLE IF NOT EXISTS ce_warehouse.s_text_rules
(
    idx INT GENERATED BY DEFAULT AS IDENTITY,

    rule_type TEXT NOT NULL
        CHECK (rule_type IN ('C', 'N', 'T')),  -- Code/Name/Text
    column_name TEXT NOT NULL
        CHECK (column_name = 'DEFAULT' OR column_name ~ '^[a-z0-9][a-z0-9_.]*[a-z0-9*]$'),
    description TEXT NOT NULL,

    allow_consecutive_ws BOOL NOT NULL DEFAULT FALSE,
    allow_leading_or_trailing_ws BOOL NOT NULL DEFAULT FALSE,
    allow_unbalanced_parenthesis BOOL NOT NULL DEFAULT FALSE,

    single_char_regex TEXT
        CHECK (
            (min_length > 1 AND single_char_regex IS NULL)
            OR (min_length = 1 AND single_char_regex IS NOT NULL)
    ),

    full_regex TEXT NOT NULL,

    -- NULL rules at the table level will override these
    min_length INT NOT NULL DEFAULT 1
        CHECK (min_length >= 1),
    max_length INT NOT NULL DEFAULT 255
        CHECK (max_length >= min_length),

    PRIMARY KEY (idx),
    UNIQUE (rule_type, column_name)
);

COMMENT ON TABLE ce_warehouse.s_text_rules
    IS 'System table - text field validation rules, see fx_val_is_text & fx_val_is_name';

/**
 * Pre-populate with known values.
 *
 * NOTE:
 *
 * - "DEFAULT" column_name is used by the validation functions when no specific rule is found for a column.
 * - Allowed text expessions are: ANY (no validation), ASCII, PRINTABLE, or regex expression (undelimited).
 *
 * Care should be taken to ensure regex expressions are valid and performant. Changes may have unexpected consequences
 * like causing all control tables  to be marked as invalid, so always test your regexes first.
 */
INSERT INTO ce_warehouse.s_text_rules (
    rule_type, column_name, description, allow_consecutive_ws, allow_leading_or_trailing_ws, allow_unbalanced_parenthesis,
    single_char_regex, full_regex, min_length, max_length
)
VALUES
    (
     'C',
     'DEFAULT',
     'Default "code" rule',
     FALSE,
     FALSE,
        FALSE,
     '^[A-Z0-9]$',
     '^[A-Z0-9][A-Z0-9_.-]*[A-Z0-9]$',
     1,
     30
    ),
    (
     'N',
     'DEFAULT',
     'Default "name" rule',
     FALSE,
     FALSE,
        FALSE,
     '^[A-Z0-9%£$€-]$',
     '^[A-Za-z0-9<>''"(%£$€][A-Za-z0-9 &/:,;.\*<>=''"()%£$€+-]*[A-Za-z0-9).%£$€+"]$',
     1,
     255
    ),
    (
     'T',
     'DEFAULT',
     'Default "text" rule',
     TRUE,
     FALSE,
     TRUE,
     'ANY',
     'ANY',
     1,
     1000
    ),
    (
     'C',
     'c_ind.code',
     'IND code',
     FALSE,
     FALSE,
     FALSE,
     NULL,
     '^[A-Z0-9][A-Z0-9<>._\-+#%£$€]*[A-Z0-9#%£$€]$',
     2,
     255
    ),
    (
     'T',
     'c_series.description',
     'SERIES description, allow for longer (& shorter) descriptions than the default text rule',
     FALSE,
     FALSE,
     FALSE,
     'ANY',
     'ANY',
     1,
     1000
    ),
    (
     'T',
     'internal_notes',
     'Internal notes',
     FALSE,
     FALSE,
     FALSE,
     'ANY',
     'ANY',
     1,
     5000
    );
