/*
 ***********************************************************************************************************
 * @file
 * x_snapshot.sql
 *
 * Internal table - snapshot values.
 *
 * Note, this is a "snapshot" of values at a (current) point in time, used for API processing, and to support
 * assorted calculations. It is built by TRIGGER and housekeeping apps.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.x__snapshot;

CREATE TABLE IF NOT EXISTS ce_warehouse.x__snapshot
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_series INT NOT NULL
        REFERENCES ce_warehouse.c__series (pk_series)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    lk_pk_pdi INT NOT NULL
        REFERENCES ce_warehouse.l__period (pk_pdi)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,  -- prevent deletion of periods with values, see app logic!!

    itype SMALLINT NOT NULL
        CHECK (itype IN (1, 2)),  -- enforce valid types: 1=actual, 2=forecast

    tgt_ifreq SMALLINT NOT NULL GENERATED ALWAYS
        AS (lk_pk_pdi / 100000000) STORED
        CHECK (tgt_ifreq IN (2, 3 , 4, 5)),  -- extract frequency from period code

    src_ifreq SMALLINT NOT NULL
        CHECK (src_ifreq IN (1, 2, 3 , 4)),  -- D->W, D->M, .., W->M, W->Q, etc

    src_last_pdi INT NOT NULL,  -- last source pdi
    src_last_value NUMERIC NOT NULL,  -- last source value (e.g. closing prices...)
    sum_value NUMERIC NOT NULL,
    num_periods INT NOT NULL,  -- number of periods included in sum_value (for averaging etc)

    ts_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_series, lk_pk_pdi, src_ifreq, itype)
);

-- Optimal index for Trigger(s)
CREATE INDEX IF NOT EXISTS x__snapshot__tgt_pdi__idx
    ON ce_warehouse.x__snapshot (fk_pk_series, lk_pk_pdi, itype);

CREATE INDEX IF NOT EXISTS x__snapshot__src_ifreq__idx
    ON ce_warehouse.x__snapshot (fk_pk_series, src_ifreq, itype);

-- It's recommended to have INDICES on foreign keys for performance!! (particularly important for large tables)
CREATE INDEX IF NOT EXISTS x__snapshot__pdi__idx
    ON ce_warehouse.x__snapshot (lk_pk_pdi);

COMMENT ON TABLE ce_warehouse.x__snapshot
    IS 'Internal table - datapoint values';
