/*
 ***********************************************************************************************************
 * @file
 * x_value.sql
 *
 * Internal table - datapoint values.
 *
 * Note: (a) this table is built up incrementally, (b) foreign refs are handled by housekeeping apps.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.x__value;

CREATE TABLE IF NOT EXISTS ce_warehouse.x__value
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_series INT NOT NULL
        REFERENCES ce_warehouse.c__series (pk_series)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,  -- prevent deletion of series with values, see app logic!!
    lk_pk_pdi INT NOT NULL
        REFERENCES ce_warehouse.l__period (pk_pdi)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,  -- prevent deletion of periods with values, see app logic!!

    -- These exist in l_freq & l_type, but aren't really worth the join
    ifreq SMALLINT NOT NULL GENERATED ALWAYS
        AS (lk_pk_pdi / 100000000) STORED
        CHECK (ifreq IN (1, 2, 3 , 4, 5)),  -- extract frequency from period code
    itype SMALLINT NOT NULL
        CHECK (itype IN (1, 2)),  -- enforce valid types: 1=actual, 2=forecast

    lk_pk_source SMALLINT NOT NULL
        REFERENCES ce_warehouse.l__source (pk_source)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    value NUMERIC NOT NULL,
    fk_pk_tip INT
        REFERENCES ce_warehouse.x__tooltip (pk_tip)
            ON UPDATE RESTRICT
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,  -- optional tooltip reference

    is_dx BOOL NOT NULL DEFAULT FALSE,  -- flag to indicate if the value is a DX value, i.e generated via DX calculation
    is_calculated BOOL NOT NULL DEFAULT FALSE,  -- flag to indicate if the value was calculated (not DX)

    error TEXT,  -- system generated
    ts_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_series, lk_pk_pdi)  -- enforce only one value per period
);

-- Optimal index for Trigger
CREATE INDEX IF NOT EXISTS x_value__series_meta__idx
    ON ce_warehouse.x__value (fk_pk_series, ifreq, itype, lk_pk_pdi);

-- It's recommended to have INDICES on foreign keys for performance!! (particularly important for large tables)
CREATE INDEX IF NOT EXISTS x_value__pdi__idx
    ON ce_warehouse.x__value (lk_pk_pdi);

CREATE INDEX IF NOT EXISTS x_value__source__idx
    ON ce_warehouse.x__value (lk_pk_source);

CREATE INDEX IF NOT EXISTS x_value__fk_pk_tip__idx
    ON ce_warehouse.x__value (fk_pk_tip);

COMMENT ON TABLE ce_warehouse.x__value
    IS 'Internal table - datapoint values';
