/*
 ***********************************************************************************************************
 * @file
 * x_series_meta.sql
 *
 * Internal table - series metadata, updated by triggers on x_value and maintained by users/apps.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.x_series_meta;

CREATE TABLE IF NOT EXISTS ce_warehouse.x_series_meta
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_series INT NOT NULL,
    ifreq SMALLINT NOT NULL
        CHECK (ifreq IN (1, 2, 3 , 4, 5)),
    itype SMALLINT NOT NULL
        CHECK (itype IN (1, 2)),

    -- SID1 is on the "series" level, SID2 and SID3 are on the "series+frequency+type" level
    sid1 TEXT NOT NULL
        CHECK (TRIM(sid1) <> ''),
    sid2 TEXT NOT NULL GENERATED ALWAYS
        AS (sid1 || '_' || (
            CASE ifreq
                WHEN 1 THEN 'D'
                WHEN 2 THEN 'W'
                WHEN 3 THEN 'M'
                WHEN 4 THEN 'Q'
                WHEN 5 THEN 'Y'
           END)) STORED,
    sid3 TEXT NOT NULL GENERATED ALWAYS
        AS (sid1 || '_' || (
            CASE ifreq
                WHEN 1 THEN 'D'
                WHEN 2 THEN 'W'
                WHEN 3 THEN 'M'
                WHEN 4 THEN 'Q'
                WHEN 5 THEN 'Y'
            END) || '_' || (
            CASE itype
                WHEN 1 THEN 'AC'
                ELSE 'F'
            END)) STORED,

    -- Financial summary fields, for performance reasons (to avoid expensive calculations on the fly)
    first_pdi INT,
    last_pdi INT,

    has_values BOOL NOT NULL DEFAULT FALSE,  -- flag to indicate if there are any values for this series/frequency/type
    new_values_utc TIMESTAMPTZ,  -- timestamp of the most recent new value
    updated_values_utc TIMESTAMPTZ,  -- timestamp of the most recent updated (or deleted) value

    FOREIGN KEY (fk_pk_series, sid1)
        REFERENCES ce_warehouse.c_series (pk_series, sid1)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,  -- prevent deletion of series with metadata, see app logic!!

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_series, ifreq, itype),  -- enforce only one record per series/frequency/type
    UNIQUE (sid3)  -- enforce unique SID3
);

-- It's recommended to have INDICES on foreign keys for performance!!
CREATE INDEX IF NOT EXISTS x_series_meta__fk_pk_series__idx
    ON ce_warehouse.x_series_meta (fk_pk_series);

COMMENT ON TABLE ce_warehouse.x_series_meta
    IS 'Internal table - series metadata, updated by triggers on x_value and maintained by users/apps';
