/*
 ***********************************************************************************************************
 * @file
 * x_tooltip.sql
 *
 * Internal table - tooltip values.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.x_tooltip;

CREATE TABLE IF NOT EXISTS ce_warehouse.x_tooltip
(
    pk_tip INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    tooltip TEXT NOT NULL
        CHECK (ce_warehouse.fx_val_is_text(tooltip, 'x_tooltip.tooltip', FALSE) IS NULL),

    PRIMARY KEY(pk_tip),
    UNIQUE (tooltip)
);

COMMENT ON TABLE ce_warehouse.x_tooltip
    IS 'Internal table - Tooltip values';
