/*
 ***********************************************************************************************************
 * @file
 * x_value.sql
 *
 * Internal table - datapoint values.
 *
 * Note: (a) this table is built up incrementally, (b) foreign refs are handled by housekeeping apps.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.x_value;

CREATE TABLE IF NOT EXISTS ce_warehouse.x_value
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    fk_pk_series INT NOT NULL
        REFERENCES ce_warehouse.c_series (pk_series)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,  -- prevent deletion of series with values, see app logic!!
    pdi INT NOT NULL
        REFERENCES ce_warehouse.l_period (pk_pdi)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,  -- prevent deletion of periods with values, see app logic!!
    ifreq SMALLINT NOT NULL GENERATED ALWAYS
        AS (pdi / 100000000) STORED
        CHECK (ifreq IN (1, 2, 3 , 4, 5)),  -- extract frequency from period code
    itype SMALLINT NOT NULL
        CHECK (itype IN (1, 2)),  -- enforce valid types: 1=actual, 2=forecast
    isource SMALLINT NOT NULL
        REFERENCES ce_warehouse.l_source (pk_source)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
    value NUMERIC NOT NULL,
    fk_pk_tip INT
        REFERENCES ce_warehouse.x_tooltip (pk_tip)
            ON UPDATE RESTRICT
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED,  -- optional tooltip reference

    is_calculated BOOL NOT NULL DEFAULT FALSE,  -- flag to indicate if the value was calculated

    error TEXT,  -- system generated
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_series, pdi)  -- enforce only one value per period
);

-- Optimal index for Trigger
CREATE INDEX IF NOT EXISTS x_value__series_meta__idx
    ON ce_warehouse.x_value (fk_pk_series, ifreq, itype, pdi);

-- It's recommended to have INDICES on foreign keys for performance!! (particularly important for large tables)
CREATE INDEX IF NOT EXISTS x_value__pdi__idx
    ON ce_warehouse.x_value (pdi);

CREATE INDEX IF NOT EXISTS x_value__isource__idx
    ON ce_warehouse.x_value (isource);

CREATE INDEX IF NOT EXISTS x_value__fk_pk_tip__idx
    ON ce_warehouse.x_value (fk_pk_tip);

COMMENT ON TABLE ce_warehouse.x_value
    IS 'Internal table - datapoint values';
