/*
 ***********************************************************************************************************
 * @file
 * x_value.sql
 *
 * Internal table - datapoint values.
 *
 * Note: (a) this table is built up incrementally, (b) foreign refs are handled by housekeeping apps.
 ***********************************************************************************************************
 */

-- DROP TABLE IF EXISTS ce_warehouse.x_value;

CREATE TABLE IF NOT EXISTS ce_warehouse.x_value
(
    idx INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fk_pk_s INT NOT NULL
        REFERENCES ce_warehouse.c_series (pk_s)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,  -- prevent deletion of series with values, see app logic!!
    pdi INT NOT NULL,  -- reference to period identifier, see housekeeping
    freq SMALLINT NOT NULL GENERATED ALWAYS
        AS (pdi / 100000000) STORED
        CHECK (freq IN (1, 2, 3 , 4, 5)),  -- extract frequency from period code
    type SMALLINT NOT NULL
        CHECK (type IN (1, 2)),  -- enforce valid types: 1=actual, 2=forecast
    source SMALLINT NOT NULL
        REFERENCES ce_warehouse.l_source (pk_src)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    value NUMERIC NOT NULL,
    fk_pk_tip INT
        REFERENCES ce_warehouse.x_tooltip (pk_tip)
        ON UPDATE CASCADE
        ON DELETE SET NULL,  -- optional tooltip reference
    is_calculated BOOLEAN NOT NULL DEFAULT FALSE,  -- flag to indicate if the value was calculated
    error TEXT,  -- optional error message for invalid values, there should never be any!!
    updated_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (idx),
    UNIQUE (fk_pk_s, pdi)  -- enforce only one value per period
);

-- Counter to track number of values per series/frequency/type, updated by trigger
CREATE INDEX IF NOT EXISTS x_value__series_value__idx
    ON ce_warehouse.x_value (fk_pk_s, freq, type);

COMMENT ON TABLE ce_warehouse.x_value
    IS 'Internal table - datapoint values';
